### ISSUE TITLE
Some divisions crashing fava completely

### ISSUE THREAD

**Issue by TiraelSedai** [beancount/fava#1000]
This works fine:

```
2019-11-02 * "Taxi home"
  Assets:MyBank:Debit     -221 RUB
  Expenses:Transport:Taxi
```

Whilst this results in the whole server going 500 Internal Server Error:

```
2019-11-02 * "Taxi home"
  Assets:MyBank:Debit     -221 RUB
  Expenses:Transport:Taxi
  Assets:SettleUp:MyPals   221/3 RUB
```

Exception details:

```
D:\OneDrive\Ledger>fava journal.bean
Running Fava on http://localhost:5000
Exception on / [GET]
Traceback (most recent call last):
  File "c:\users\tirae\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\tirae\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\tirae\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\tirae\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\tirae\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1947, in full_dispatch_request
    rv = self.preprocess_request()
  File "c:\users\tirae\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2235, in preprocess_request
    func(request.endpoint, request.view_args)
  File "c:\users\tirae\appdata\local\programs\python\python37-32\lib\site-packages\fava\application.py", line 230, in _pull_beancount_file
    _load_file()
  File "c:\users\tirae\appdata\local\programs\python\python37-32\lib\site-packages\fava\application.py", line 97, in _load_file
    ledger = FavaLedger(filepath)
  File "c:\users\tirae\appdata\local\programs\python\python37-32\lib\site-packages\fava\core\__init__.py", line 174, in __init__
    self.load_file()
  File "c:\users\tirae\appdata\local\programs\python\python37-32\lib\site-packages\fava\core\__init__.py", line 182, in load_file
    [(self.beancount_file_path, True)], None, None, None
  File "c:\users\tirae\appdata\local\programs\python\python37-32\lib\site-packages\beancount\loader.py", line 471, in _load
    entries, balance_errors = booking.book(entries, options_map)
  File "c:\users\tirae\appdata\local\programs\python\python37-32\lib\site-packages\beancount\parser\booking.py", line 38, in book
    booking_methods)
  File "c:\users\tirae\appdata\local\programs\python\python37-32\lib\site-packages\beancount\parser\booking_full.py", line 112, in book
    entries, errors, _ = _book(entries, options_map, methods)
  File "c:\users\tirae\appdata\local\programs\python\python37-32\lib\site-packages\beancount\parser\booking_full.py", line 194, in _book
    tolerances)
  File "c:\users\tirae\appdata\local\programs\python\python37-32\lib\site-packages\beancount\parser\booking_full.py", line 855, in interpolate_group
    units_number)
  File "c:\users\tirae\appdata\local\programs\python\python37-32\lib\site-packages\beancount\core\interpolate.py", line 347, in quantize_with_tolerance
    number = number.quantize(quantum)
decimal.InvalidOperation: [<class 'decimal.InvalidOperation'>]
```

**Comment by TiraelSedai** [comment]
I'm not insisting that infinite decimals like 73.(6) are valid and should be displayed, but for sure I want to see some error explaining that the exception occurred while reading specific line of my beancount file and not just some generic 500.

**Comment by yagebu** [comment]
This is a Beancount bug - could you report it on the Beancount bug tracker?
