### ISSUE TITLE
Using Beancount Account Types Option

### ISSUE THREAD

**Issue by ikwtif** [beancount/fava#1026]
Handling beancount options for the account types does not work for me. 
I set the default account types at the top of the beancount file to my language like this
```
option "name_assets" "Activa"
option "name_equity" "Aandelen"
option "name_expenses" "Uitgaven"
option "name_income" "Inkomsten"
option "name_liabilities" "Passiva"
```
Doing this breaks `Income statement, Balance sheet, etc`
This also produces the error in the `Holdings` section on fava
```
Traceback (most recent call last):
  File "C:\Users\Dieter\AppData\Local\Programs\Python\Python37\lib\cmd.py", line 214, in onecmd
    func = getattr(self, 'do_' + cmd)
AttributeError: 'QueryShell' object has no attribute 'do_SELECT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\documenten\coding\import beancount\env\lib\site-packages\beancount\query\shell.py", line 271, in run_parser
    self.dispatch(statement)
  File "d:\documenten\coding\import beancount\env\lib\site-packages\beancount\query\shell.py", line 251, in dispatch
    return method(statement)
  File "d:\documenten\coding\import beancount\env\lib\site-packages\fava\core\query_shell.py", line 95, in on_Select
    c_query, self.entries, self.options_map
  File "d:\documenten\coding\import beancount\env\lib\site-packages\beancount\query\query_execute.py", line 316, in execute_query
    if c_where is None or c_where(context):
  File "d:\documenten\coding\import beancount\env\lib\site-packages\beancount\query\query_compile.py", line 121, in __call__
    return self.operator(self.left(context), self.right(context))
  File "d:\documenten\coding\import beancount\env\lib\site-packages\beancount\query\query_env.py", line 395, in __call__
    index, name = account_types.get_account_sort_key(context.account_types, args[0])
  File "d:\documenten\coding\import beancount\env\lib\site-packages\beancount\core\account_types.py", line 46, in get_account_sort_key
    return (account_types.index(get_account_type(account_name)), account_name)
ValueError: tuple.index(x): x not in tuple
```
Not sure if there's a special way to use the account types option in the beancount file for fava? Or if it is because the `DEFAULT_ACCOUNT_TYPES` are hardcoded inside `account_types.py`. I removed the options for the account types in the beancount file and changed all account types to the default ones and that worked. So I assume this would have to be a new feature for this to work?

**Comment by ikwtif** [comment]
I failed to notice the error happened inside beancount. So I tried a few things and found the issue.  
I have my *.beancount files split into 
```
journal.beancount
transactions.beancount
accounts.beancount
```
and load them through `journal.beancount`, which points to the other beancount files
My account type options where not inside the journal file, which caused them to not load properly.
