### ISSUE TITLE
jinja2.exceptions.TemplateNotFound: _layout.html

### ISSUE THREAD

**Issue by kenkangxgwe** [beancount/fava#1058]
Downloaded and installed the latest commit 9aa5fa4fce3ce10faf1e792dd70e3a5179fe15d8 of the master branch, and failed to visit the web page.

```
[2020-02-16 03:18:27,207] ERROR in app: Exception on /my-personal-ledger/income_statement/ [GET]
Traceback (most recent call last):
  File "d:\programs\anaconda3\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\programs\anaconda3\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\programs\anaconda3\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\programs\anaconda3\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "d:\programs\anaconda3\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\programs\anaconda3\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\programs\anaconda3\lib\site-packages\fava\application.py", line 331, in report
    return render_template("_layout.html", active_page=report_name)
  File "d:\programs\anaconda3\lib\site-packages\flask\templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "d:\programs\anaconda3\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "d:\programs\anaconda3\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "d:\programs\anaconda3\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "d:\programs\anaconda3\lib\site-packages\jinja2\loaders.py", line 117, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "d:\programs\anaconda3\lib\site-packages\flask\templating.py", line 57, in get_source
    return self._get_source_fast(environment, template)
  File "d:\programs\anaconda3\lib\site-packages\flask\templating.py", line 85, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _layout.html
```

**Comment by kenkangxgwe** [comment]
The error above seems fixed when I upgraded to the latest release. But I got another error:
```
[2020-02-17 00:20:14,514] ERROR in app: Exception on /my-personal-ledger/api/changed/ [GET]
Traceback (most recent call last):
  File "d:\programs\anaconda3\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\programs\anaconda3\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\programs\anaconda3\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\programs\anaconda3\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "d:\programs\anaconda3\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\programs\anaconda3\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\programs\anaconda3\lib\site-packages\fava\json_api.py", line 32, in _wrapper
    return jsonify({"success": True, "data": func(*args, **kwargs)})
  File "d:\programs\anaconda3\lib\site-packages\flask\json.py", line 251, in jsonify
    if current_app.config['JSONIFY_PRETTYPRINT_REGULAR'] and not request.is_xhr:
  File "d:\programs\anaconda3\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'is_xhr'
```

**Comment by yagebu** [comment]
This looks like a problem with outdated dependencies, you should try to update them.

**Comment by kenkangxgwe** [comment]
Thanks. Fixed by upgrading `flask` to the latest version.
