### ISSUE TITLE
decimal.InvalidOperation error when locale is set

### ISSUE THREAD

**Issue by mbudde** [beancount/fava#1070]
Fava fails with an 500 error given the following journal:
```
option "operating_currency" "DKK"

2000-01-01 custom "fava-option" "locale" "da_DK"

2000-01-01 open Assets:Foo DKK
2000-01-01 open Income:Bar DKK

2019-02-01 * "Transaction"
    Assets:Foo                                               (5/12) DKK
    Income:Bar

2019-03-01 * "Transaction"
    Assets:Foo                                               (5/12) DKK
    Income:Bar

2019-04-01 * "Transaction"
    Assets:Foo                                               (5/12) DKK
    Income:Bar
```

<details>
<summary>Stacktrace</summary>
<pre>
Exception on /beancount/income_statement/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/fava/application.py", line 331, in report
    return render_template("_layout.html", active_page=report_name)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/fava/templates/_layout.html", line 42, in top-level template code
    <div id="svelte-charts"></div>
  File "/usr/local/lib/python3.7/site-packages/fava/templates/_layout.html", line 46, in block "content"
    {% else %}
  File "/usr/local/lib/python3.7/site-packages/fava/templates/income_statement.html", line 12, in top-level template code
    {{ tree_table.tree(ledger.root_tree.get(ledger.options['name_income'])) }}
  File "/usr/local/lib/python3.7/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "/usr/local/lib/python3.7/site-packages/fava/templates/_tree_table.html", line 33, in template
    {% for account in ([account_node] if account_node.name else account_node.children) if account|should_show recursive %}
  File "/usr/local/lib/python3.7/site-packages/fava/templates/_tree_table.html", line 46, in template
    <span class="balance-children">{{ render_diff_and_number(balance_children, cost_children, currency) }}</span>
  File "/usr/local/lib/python3.7/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "/usr/local/lib/python3.7/site-packages/fava/templates/_tree_table.html", line 17, in template
    <span class="number">{{ num|format_currency(currency) }}</span>
  File "/usr/local/lib/python3.7/site-packages/fava/template_filters.py", line 92, in format_currency
    return g.ledger.format_decimal(value, currency)
  File "/usr/local/lib/python3.7/site-packages/fava/core/number.py", line 75, in __call__
    return pattern.apply(value, self.locale)
  File "/usr/local/lib/python3.7/site-packages/babel/numbers.py", line 996, in apply
    number = self._quantize_value(value, locale, frac_prec)
  File "/usr/local/lib/python3.7/site-packages/babel/numbers.py", line 1065, in _quantize_value
    rounded = value.quantize(quantum)
decimal.InvalidOperation: [<class 'decimal.InvalidOperation'>]
</pre>
</details>

If the `locale` option line is removed the error disappears. It does not seem to depend on which locale is specified. Removing one of the transactions also makes the error disappear for some reason.

**Comment by yagebu** [comment]
From my initial debug it looked this could be a bug in Babel, due to us trying to render a currency with a high number of decimal places.
