### ISSUE TITLE
cannot import name 'FavaExtensionBase' from 'fava.ext': but works second time

### ISSUE THREAD

**Issue by tbm** [beancount/fava#1095]
I wanted to try fava_investor but it fails because FavaExtensionBase can't be imported.  I can reproduce this in the python3 REPL.  Interestingly, it works when I call it a second time. Any idea?

```
python3
Python 3.7.3 (default, Dec 20 2019, 18:57:59) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from fava.ext import FavaExtensionBase
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tbm/.local/lib/python3.7/site-packages/fava/ext/__init__.py", line 11, in <module>
    from fava.core.helpers import BeancountError
  File "/home/tbm/.local/lib/python3.7/site-packages/fava/core/__init__.py", line 47, in <module>
    from fava.core.extensions import ExtensionModule
  File "/home/tbm/.local/lib/python3.7/site-packages/fava/core/extensions.py", line 12, in <module>
    from fava.ext import FavaExtensionBase
ImportError: cannot import name 'FavaExtensionBase' from 'fava.ext' (/home/tbm/.local/lib/python3.7/site-packages/fava/ext/__init__.py)
>>> from fava.ext import FavaExtensionBase
>>> 
```

**Comment by tbm** [comment]
I reinstalled fava and it's working now.

**Comment by yagebu** [comment]
This is due to some circular imports.
