### ISSUE TITLE
Error 503 / Tracebacks when running statistics

### ISSUE THREAD

**Issue by jorgeml** [beancount/fava#1178]
I am getting a traceback when clicking on "Statistics":

`127.0.0.1 - - [14/Nov/2020 10:42:10] "GET /jorges-beancount-file/statistics/?partial=true HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.9/site-packages/werkzeug/middleware/profiler.py", line 105, in __call__
    profile.runcall(runapp)
  File "/usr/lib64/python3.9/cProfile.py", line 109, in runcall
    return func(*args, **kw)
  File "/usr/lib/python3.9/site-packages/werkzeug/middleware/profiler.py", line 97, in runapp
    app_iter = self._app(environ, catching_start_response)
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/home/jorgeml/.local/lib/python3.9/site-packages/fava/application.py", line 332, in report
    return render_template("_layout.html", active_page=report_name)
  File "/usr/lib/python3.9/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/usr/lib/python3.9/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/var/home/jorgeml/.local/lib/python3.9/site-packages/fava/templates/_layout.html", line 44, in top-level template code
    {% block content %}
  File "/var/home/jorgeml/.local/lib/python3.9/site-packages/fava/templates/_layout.html", line 48, in block "content"
    {% include active_page + '.html' %}
  File "/var/home/jorgeml/.local/lib/python3.9/site-packages/fava/templates/statistics.html", line 77, in top-level template code
    {% for group in ledger.entries|groupby('__class__.__name__') %}
  File "/usr/lib/python3.9/site-packages/jinja2/filters.py", line 987, in do_groupby
    for key, values in groupby(sorted(value, key=expr), expr)
TypeError: '<' not supported between instances of 'types.GenericAlias' and 'types.GenericAlias`

Versions:
beancount                2.3.3
fava                     1.16
Flask                    1.1.2
Jinja2                   2.11.2
Werkzeug                 1.0.1

The broswer is Firefox 82.0.3.

Thanks for looking into this.

**Comment by yagebu** [comment]
Thank you for the bug report :) This happens on Python 3.9 only (NamedTuple changed a bit) and is already fixed in master (by https://github.com/beancount/fava/commit/1ad91f01955a1b1a69e0886273f2c71ed33d65d6)
