### ISSUE TITLE
MX Linux, Python 3.5 and 3.9 installed

### ISSUE THREAD

**Issue by dnjkalnvfjdkln** [beancount/fava#1185]
Hello,

Posted this on anther website as well, sorry about that.

New to computers and was trying to find the following answer.
Installed Beancount, works!
Installed fava with pip, good

installed python3 version 3.5, in usr/bin
manualling installed pything 3.9 in usr/local/bin

when I try to run the fava program:

command: fava /home/family281/Documents/Emacs/2020beancount.beancount
command and path to file:

Traceback (most recent call last):
  File "/usr/local/bin/fava", line 7, in <module>
    from fava.cli import main
  File "/usr/local/lib/python3.5/dist-packages/fava/cli.py", line 89
    print(f"Running Fava on http://{host}:{port}")
                                                ^
SyntaxError: invalid syntax

I use the following from the chat on Fava website:
$ python3.9 /usr/local/bin/fava /home/family281/Documents/Emacs/2020beancount.beancount
Traceback (most recent call last):
  File "/usr/local/bin/fava", line 7, in <module>
    from fava.cli import main
ModuleNotFoundError: No module named 'fava'

1 error goes away, 1 remains

If you could please assist, I am assuming I installed something wrong.

THank You!

**Comment by dnjkalnvfjdkln** [comment]
Was able to fix, switch the 3.5 to 3.9
Thank you!
