### ISSUE TITLE
Fava shows Internal Server Error 500

### ISSUE THREAD

**Issue by bmcgee** [beancount/fava#1186]
No matter what I try to do to install fava (pipenv / conda / pip3 / etc...) I receive the same message on running it:

```Running Fava on http://localhost:5000
Exception on / [GET]
Traceback (most recent call last):
  File "/Users/brianmcgee/miniconda3/envs/beancount/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/brianmcgee/miniconda3/envs/beancount/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/brianmcgee/miniconda3/envs/beancount/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/brianmcgee/miniconda3/envs/beancount/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/brianmcgee/miniconda3/envs/beancount/lib/python3.6/site-packages/flask/app.py", line 1948, in full_dispatch_request
    rv = self.preprocess_request()
  File "/Users/brianmcgee/miniconda3/envs/beancount/lib/python3.6/site-packages/flask/app.py", line 2236, in preprocess_request
    func(request.endpoint, request.view_args)
  File "/Users/brianmcgee/miniconda3/envs/beancount/lib/python3.6/site-packages/fava/application.py", line 230, in _pull_beancount_file
    _load_file()
  File "/Users/brianmcgee/miniconda3/envs/beancount/lib/python3.6/site-packages/fava/application.py", line 101, in _load_file
    ledger = FavaLedger(filepath)
  File "/Users/brianmcgee/miniconda3/envs/beancount/lib/python3.6/site-packages/fava/core/__init__.py", line 204, in __init__
    self.load_file()
  File "/Users/brianmcgee/miniconda3/envs/beancount/lib/python3.6/site-packages/fava/core/__init__.py", line 212, in load_file
    [(self.beancount_file_path, True)], None, None, None
  File "/Users/brianmcgee/miniconda3/envs/beancount/lib/python3.6/site-packages/beancount/loader.py", line 500, in _load
    sources, log_timings, encoding)
  File "/Users/brianmcgee/miniconda3/envs/beancount/lib/python3.6/site-packages/beancount/loader.py", line 370, in _parse_recursive
    assert path.isabs(source)
AssertionError
Exception on /favicon.ico/ [GET]
Traceback (most recent call last):
  File "/Users/brianmcgee/miniconda3/envs/beancount/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/brianmcgee/miniconda3/envs/beancount/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/brianmcgee/miniconda3/envs/beancount/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/brianmcgee/miniconda3/envs/beancount/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/brianmcgee/miniconda3/envs/beancount/lib/python3.6/site-packages/flask/app.py", line 1948, in full_dispatch_request
    rv = self.preprocess_request()
  File "/Users/brianmcgee/miniconda3/envs/beancount/lib/python3.6/site-packages/flask/app.py", line 2236, in preprocess_request
    func(request.endpoint, request.view_args)
  File "/Users/brianmcgee/miniconda3/envs/beancount/lib/python3.6/site-packages/fava/application.py", line 232, in _pull_beancount_file
    if g.beancount_file_slug not in app.config["FILE_SLUGS"]:```

**Comment by yagebu** [comment]
How are you running Fava? From the first error, it seems that the path to the Beancount file that was passed to Fava is not an absolute path.

**Comment by bmcgee** [comment]
running it after installing with pip in a conda environment in that instance inside the .beancount files parent directory. it seems to run fine when I run with sudo – wondering if it's something to do w/ my python's installs permission or something.

**Comment by yagebu** [comment]
If it works when run with `sudo`, then that definitely points to some problem with your Conda/Python/whatever environment. Reinstalling Fava and updating its dependencies might help. Other than that there's not really any help that I can offer.
