### ISSUE TITLE
Fava not shutting down on Ctrl-C in terminal

### ISSUE THREAD

**Issue by mhansen** [beancount/fava#1205]
Hi, first up, thank you for fava, it's great, I love the tool, it really helps me understand my finances.

A small regression: it seems like Ctrl-C (SIGINT) in the terminal doesn't quit fava any more. I think it used to exit cleanly on Ctrl-C on older versions.

```
$ fava --version
fava, version 1.17

$ fava joint.beancount
Running Fava on http://localhost:5000
^CKeyboard Interrupt: shutting down
```

I have to Ctrl-C three times (shown below as `^C`), and this is the stack trace when it finally does exit:

```
fava joint.beancount
Running Fava on http://localhost:5000
^CKeyboard Interrupt: shutting down
^C
Aborted!
^CException ignored in: <module 'threading' from '/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py'>
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 1424, in _shutdown
    lock.acquire()
KeyboardInterrupt: 
```

Perhaps not a very useful stacktrace considering there's no fava code in that stacktrace though.

**Comment by yagebu** [comment]
I can't reproduce this. Does this always happen? Is the shutdown maybe just delayed and happens after a few seconds?

**Comment by mhansen** [comment]
Has happened 4/4 recent times for me. I wonder if the server is handling a
long request in lame duck mode or something

**Comment by mhansen** [comment]
I tried running the steps to debug a hung process here, getting a thread dump:

https://dzone.com/articles/inspecting-thread-dumps-hung

```
$ env PYTHONFAULTHANDLER=true fava foo.beancount
^C
Running Fava on http://localhost:5000
^CKeyboard Interrupt: shutting down
^Z⏎
$ jobs
Job     Group   State   Command
1       43574   stopped env PYTHONFAULTHANDLER=true fava foo.beancount
$ kill -ABRT 43574
$ fg
> fg
Send job 1, 'env PYTHONFAULTHANDLER=true fava foo.beancount' to foreground
Fatal Python error: Aborted
Thread 0x0000700017f49000 (most recent call first):
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 312 in wait
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/queue.py", line 171 in get
  File "/usr/local/lib/python3.9/site-packages/cheroot/workers/threadpool.py", line 110 in run
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 950 in _bootstrap_inner
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 908 in _bootstrap

Thread 0x0000700016f46000 (most recent call first):
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 312 in wait
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/queue.py", line 171 in get
  File "/usr/local/lib/python3.9/site-packages/cheroot/workers/threadpool.py", line 110 in run
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 950 in _bootstrap_inner
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 908 in _bootstrap

Thread 0x0000700015f43000 (most recent call first):
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 312 in wait
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/queue.py", line 171 in get
  File "/usr/local/lib/python3.9/site-packages/cheroot/workers/threadpool.py", line 110 in run
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 950 in _bootstrap_inner
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 908 in _bootstrap

Thread 0x0000700014f40000 (most recent call first):
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 312 in wait
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/queue.py", line 171 in get
  File "/usr/local/lib/python3.9/site-packages/cheroot/workers/threadpool.py", line 110 in run
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 950 in _bootstrap_inner
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 908 in _bootstrap

Thread 0x0000700013f3d000 (most recent call first):
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 312 in wait
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/queue.py", line 171 in get
  File "/usr/local/lib/python3.9/site-packages/cheroot/workers/threadpool.py", line 110 in run
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 950 in _bootstrap_inner
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 908 in _bootstrap

Thread 0x0000700012f3a000 (most recent call first):
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 312 in wait
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/queue.py", line 171 in get
  File "/usr/local/lib/python3.9/site-packages/cheroot/workers/threadpool.py", line 110 in run
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 950 in _bootstrap_inner
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 908 in _bootstrap

Thread 0x0000700011f37000 (most recent call first):
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 312 in wait
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/queue.py", line 171 in get
  File "/usr/local/lib/python3.9/site-packages/cheroot/workers/threadpool.py", line 110 in run
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 950 in _bootstrap_inner
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 908 in _bootstrap

Thread 0x0000700010f34000 (most recent call first):
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 312 in wait
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/queue.py", line 171 in get
  File "/usr/local/lib/python3.9/site-packages/cheroot/workers/threadpool.py", line 110 in run
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 950 in _bootstrap_inner
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 908 in _bootstrap

Thread 0x000070000ff31000 (most recent call first):
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 312 in wait
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/queue.py", line 171 in get
  File "/usr/local/lib/python3.9/site-packages/cheroot/workers/threadpool.py", line 110 in run
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 950 in _bootstrap_inner
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 908 in _bootstrap

Thread 0x000070000ef2e000 (most recent call first):
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 312 in wait
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/queue.py", line 171 in get
  File "/usr/local/lib/python3.9/site-packages/cheroot/workers/threadpool.py", line 110 in run
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 950 in _bootstrap_inner
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 908 in _bootstrap

Current thread 0x000000010d8dbe00 (most recent call first):
  File "/usr/local/lib/python3.9/site-packages/cheroot/server.py", line 2071 in stop
  File "/usr/local/lib/python3.9/site-packages/cheroot/server.py", line 1715 in safe_start
  File "/usr/local/lib/python3.9/site-packages/fava/cli.py", line 90 in main
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610 in invoke
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066 in invoke
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782 in main
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829 in __call__
  File "/usr/local/bin/fava", line 8 in <module>
fish: Job 1, 'env PYTHONFAULTHANDLER=true fav…' terminated by signal SIGABRT (Abort)
```

**Comment by mhansen** [comment]
That `line 2071 in stop` is, on my machine, a `time.sleep(0.1)` call in the server stack:

```
    def stop(self):  # noqa: C901  # FIXME
        """Gracefully shutdown a server that is serving forever."""
        self.ready = False
        if self._start_time is not None:
            self._run_time += (time.time() - self._start_time)
        self._start_time = None

        # ensure serve is no longer accessing socket, connections
        while self.serving:
            time.sleep(0.1)
```

Looks like that `sleep` is not present in the latest version of `cheroot`: https://github.com/cherrypy/cheroot/blob/master/cheroot/server.py

**Comment by mhansen** [comment]
https://github.com/cherrypy/cheroot/commit/91723ea753408ee66926374e633cb7b5364a14ef looks like it moved the `sleep` call into `self._connections.stop()` which calls

```
        while self._serving:
             time.sleep(0.01)
```

**Comment by mhansen** [comment]
Found the upstream issue: https://github.com/cherrypy/cheroot/issues/328

**Comment by mhansen** [comment]
I fixed this by upgrading cheroot past v8.4.6.

```
$ pip3 install cheroot --upgrade
```

**Comment by yagebu** [comment]
Thanks for debugging this so thoroughly :)

**Comment by mhansen** [comment]
No worries, thanks for attempting the repro. This is some great software
you've made, it really helps me with my finances every tax season.

All the best, Mark.
