### ISSUE TITLE
Internal server error when trying to reduce position by more than is in account

### ISSUE THREAD

**Issue by falsifian** [beancount/fava#1570]
At `main` (commit 8066b202cc6febb47005eb338c0d5fe2b85d744e), with the following simple ledger:

```
option "operating_currency" "USD"

2019-01-01 open Assets:Cash
2019-01-01 open Assets:Stock

2019-01-01 * "buy"
  Assets:Stock  0.1 ACME {80.00 USD}
  Assets:Cash

2020-01-01 * "sell"
  Assets:Stock  -1.0 ACME {}
  Assets:Cash
```

I get a 500 Internal Server Error, and on the terminal where fava is running, I see:

```
Starting Fava on http://127.0.0.1:5000
Exception on /beancount/income_statement/ [GET]
Traceback (most recent call last):
  File "/home/falsifian/.local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/falsifian/.local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/falsifian/.local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/falsifian/.local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/falsifian/.local/lib/python3.10/site-packages/fava/application.py", line 359, in report
    return render_template("_layout.html", active_page=report_name)
  File "/home/falsifian/.local/lib/python3.10/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/home/falsifian/.local/lib/python3.10/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/home/falsifian/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/falsifian/.local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/falsifian/.local/lib/python3.10/site-packages/fava/templates/_layout.html", line 44, in top-level template code
    <script type="application/json" id="ledger-data">{{ get_ledger_data()|tojson }}</script>
  File "/home/falsifian/.local/lib/python3.10/site-packages/jinja2/filters.py", line 1688, in do_tojson
    return htmlsafe_json_dumps(value, dumps=dumps, **kwargs)
  File "/home/falsifian/.local/lib/python3.10/site-packages/jinja2/utils.py", line 658, in htmlsafe_json_dumps
    dumps(obj, **kwargs)
  File "/home/falsifian/.local/lib/python3.10/site-packages/fava/core/charts.py", line 100, in dumps
    return ENCODER.encode(obj)
  File "/usr/local/lib/python3.10/site-packages/simplejson/encoder.py", line 297, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.10/site-packages/simplejson/encoder.py", line 379, in iterencode
    return _iterencode(o, 0)
  File "/home/falsifian/.local/lib/python3.10/site-packages/fava/core/charts.py", line 83, in default
    return JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.10/site-packages/simplejson/encoder.py", line 273, in default
    raise TypeError('Object of type %s is not JSON serializable' %
TypeError: Object of type type is not JSON serializable
```

**Comment by falsifian** [comment]
I have beancount 2.3.5 with Python 3.10.10.

**Comment by yagebu** [comment]
Thanks for the report :)
