### ISSUE TITLE
I got this error when I visit Options menu, I used /tests/data/long-example.beancount file, anyone can help me? thanks.

### ISSUE THREAD

**Issue by 2007lf** [beancount/fava#1581]
Exception on /long-example/options/ [GET]
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/python3/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/python3/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/python3/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/python3/lib/python3.7/site-packages/fava/application.py", line 359, in report
    return render_template("_layout.html", active_page=report_name)
  File "/usr/local/python3/lib/python3.7/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/usr/local/python3/lib/python3.7/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/usr/local/python3/lib/python3.7/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/python3/lib/python3.7/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/usr/local/python3/lib/python3.7/site-packages/fava/templates/_layout.html", line 31, in top-level template code
    {% block content %}
  File "/usr/local/python3/lib/python3.7/site-packages/fava/templates/_layout.html", line 35, in block 'content'
    {% include active_page + '.html' %}
  File "/usr/local/python3/lib/python3.7/site-packages/fava/templates/options.html", line 10, in top-level template code
    {% for key, value in ledger.fava_options|dataclass_asdict|dictsort %}
  File "/usr/local/python3/lib/python3.7/dataclasses.py", line 1013, in asdict
    return _asdict_inner(obj, dict_factory)
  File "/usr/local/python3/lib/python3.7/dataclasses.py", line 1020, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
  File "/usr/local/python3/lib/python3.7/dataclasses.py", line 1024, in _asdict_inner
    return type(obj)(_asdict_inner(v, dict_factory) for v in obj)
TypeError: __new__() missing 1 required positional argument: 'day'

**Comment by yagebu** [comment]
Hi, thanks for the report :) I can't reproduce this (might be that this only happens on older Python...). I've tried something that might fix it in #1583. Could you try installing from main and seeing if that fixed it?

**Comment by 2007lf** [comment]
Thank u, when I try to re-install from git clone and pip3 install ./ , I find other question, the folder src/fava/static/ was empty, no css and js file, web doesn't have any styles, but use pip3 install fava no problem, 🤔

**Comment by yagebu** [comment]
See https://beancount.github.io/fava/development.html for how to install from main.

I've also just pushed out v1.24.4 which includes that fix
