### ISSUE TITLE
UnicodeDecodeError accessing the browser editor

### ISSUE THREAD

**Issue by erpreciso** [beancount/fava#1601]
### Error

in browser, click on 'Editor' trying to access the built-in text editor triggers a red disappearing popup and the following console output.

```
(acc) C:\Users\c740\OneDrive\areas\accounting>fava ledgers\imported.beancount
Starting Fava on http://127.0.0.1:5000
Exception on /beancount/editor/ [GET]
Traceback (most recent call last):
  File "C:\Users\c740\miniconda3\envs\acc\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\c740\miniconda3\envs\acc\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\c740\miniconda3\envs\acc\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\c740\miniconda3\envs\acc\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\c740\miniconda3\envs\acc\lib\site-packages\fava\application.py", line 349, in report
    return render_template("_layout.html", active_page=report_name)
  File "C:\Users\c740\miniconda3\envs\acc\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "C:\Users\c740\miniconda3\envs\acc\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "C:\Users\c740\miniconda3\envs\acc\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\c740\miniconda3\envs\acc\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\c740\miniconda3\envs\acc\lib\site-packages\fava\templates\_layout.html", line 44, in top-level template code
    {% block content %}
  File "C:\Users\c740\miniconda3\envs\acc\lib\site-packages\fava\templates\_layout.html", line 48, in block 'content'
    {% include active_page + '.html' %}
  File "C:\Users\c740\miniconda3\envs\acc\lib\site-packages\fava\templates\editor.html", line 2, in top-level template code
    {% set source, sha256sum = ledger.file.get_source(file_path) %}
  File "C:\Users\c740\miniconda3\envs\acc\lib\site-packages\fava\core\file.py", line 83, in get_source
    source = decode(contents)
  File "C:\Users\c740\miniconda3\envs\acc\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 283: invalid start byte

```

### Ledger

```
;; -*- mode: beancount -*-


2023-04-03 * "Entgelt Visa-Kreditkarte Zeitraum: 01.03.2023 bis 31.03.2023 Ref. 9F2C1LVN2U9U42FG/658516"
  Expenses:Other:BankCommissions:Comdirect
  Assets:Checking:Comdirect                 -1.90 EUR
    source_desc: "03.04.2023;31.03.2023;Kontoführungsentgelt; Buchungstext: Entgelt Visa-Kreditkarte Zeitraum: 01.03.2023 bis 31.03.2023 Ref. 9F2C1LVN2U9U42FG/658516;-1,90;"

2023-04-02 open Expenses:Other:BankCommissions:Comdirect
2023-04-02 open Assets:Checking:Comdirect
option "operating_currency" "EUR"

```

### Possible related issues

In issue #983, fava returns a 'file not found' but without crashing.

### System info

```
(acc) C:\Users\c740\OneDrive\areas\accounting>systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows 11 Home
OS Version:                10.0.22621 N/A Build 22621
```
### browser

`Chrome Version 112.0.5615.138 (Official Build) (64-bit)`

### conda list

```  
(acc) C:\Users\c740\OneDrive\areas\accounting>conda list
# packages in environment at C:\Users\c740\miniconda3\envs\acc:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12             pyhd3eb1b0_0
appdirs                   1.4.4                    pypi_0    pypi
arrow                     1.2.3           py310haa95532_0
asgiref                   3.6.0                    pypi_0    pypi
astroid                   2.11.7          py310haa95532_0
atomicwrites              1.4.0                      py_0
attrs                     22.1.0          py310haa95532_0
autopep8                  1.6.0              pyhd3eb1b0_1
babel                     2.11.0          py310haa95532_0
backcall                  0.2.0              pyhd3eb1b0_0
bcrypt                    3.2.0           py310h2bbff1b_1
beancount                 2.3.5                    pypi_0    pypi
beancount-categorizer     0.1.dev12+g9900eaa          pypi_0    pypi
beancount-reds-plugins    0.3.0                    pypi_0    pypi
beangrow                  0.0.0                    pypi_0    pypi
beautifulsoup4            4.11.1          py310haa95532_0
binaryornot               0.4.4              pyhd3eb1b0_1
black                     22.6.0          py310haa95532_0
blas                      1.0                         mkl
bleach                    4.1.0              pyhd3eb1b0_0
bottle                    0.12.23                  pypi_0    pypi
bottleneck                1.3.5           py310h9128911_0
brotli                    1.0.9                h2bbff1b_7
brotli-bin                1.0.9                h2bbff1b_7
brotlipy                  0.7.0           py310h2bbff1b_1002
bs4                       0.0.1                    pypi_0    pypi
bzip2                     1.0.8                he774522_0
ca-certificates           2023.01.10           haa95532_0
cachetools                5.3.0                    pypi_0    pypi
camelot-py                0.9.0                    pypi_0    pypi
certifi                   2022.12.7       py310haa95532_0
cffi                      1.15.1          py310h2bbff1b_3
chardet                   4.0.0           py310haa95532_1003
charset-normalizer        2.0.4              pyhd3eb1b0_0
cheroot                   8.6.0                    pypi_0    pypi
click                     8.0.4           py310haa95532_0
click-aliases             1.0.1                    pypi_0    pypi
cloudpickle               2.0.0              pyhd3eb1b0_0
colorama                  0.4.6           py310haa95532_0
comm                      0.1.2           py310haa95532_0
contourpy                 1.0.5           py310h59b6b97_0
cookiecutter              1.7.3              pyhd3eb1b0_0
cryptography              38.0.4          py310h21b164f_0
cycler                    0.11.0             pyhd3eb1b0_0
debugpy                   1.5.1           py310hd77b12b_0
decorator                 5.1.1              pyhd3eb1b0_0
defusedxml                0.7.1              pyhd3eb1b0_0
diff-match-patch          20200713           pyhd3eb1b0_0
dill                      0.3.6           py310haa95532_0
django                    4.1.7                    pypi_0    pypi
docutils                  0.18.1          py310haa95532_3
elixir                    0.7.1                    pypi_0    pypi
entrypoints               0.4             py310haa95532_0
et-xmlfile                1.1.0                    pypi_0    pypi
exceptiongroup            1.1.0                    pypi_0    pypi
fava                      1.23.1                   pypi_0    pypi
fava-income-reports       0.1.dev13+g8557507          pypi_0    pypi
fava-investor             0.5.0                    pypi_0    pypi
fava-portfolio-returns    0.1.dev10+g2621ef7          pypi_0    pypi
flake8                    4.0.1              pyhd3eb1b0_1
flask                     2.2.2                    pypi_0    pypi
flask-babel               2.0.0                    pypi_0    pypi
flit-core                 3.6.0              pyhd3eb1b0_0
fonttools                 4.25.0             pyhd3eb1b0_0
freetype                  2.12.1               ha860e81_0
frozendict                2.3.4                    pypi_0    pypi
glib                      2.69.1               h5dc1a3c_2
google-api-core           2.11.0                   pypi_0    pypi
google-api-python-client  2.74.0                   pypi_0    pypi
google-auth               2.16.0                   pypi_0    pypi
google-auth-httplib2      0.1.0                    pypi_0    pypi
googleapis-common-protos  1.58.0                   pypi_0    pypi
gst-plugins-base          1.18.5               h9e645db_0
gstreamer                 1.18.5               hd78058f_0
html5lib                  1.1                      pypi_0    pypi
httplib2                  0.21.0                   pypi_0    pypi
icu                       58.2                 ha925a31_3
idna                      3.4             py310haa95532_0
imagesize                 1.4.1           py310haa95532_0
importlib-metadata        4.11.3          py310haa95532_0
importlib_metadata        4.11.3               hd3eb1b0_0
inflection                0.5.1           py310haa95532_0
iniconfig                 2.0.0                    pypi_0    pypi
intel-openmp              2021.4.0          haa95532_3556
intervaltree              3.1.0              pyhd3eb1b0_0
ipykernel                 6.19.2          py310h9909e9c_0
ipython                   7.31.1          py310haa95532_1
ipython_genutils          0.2.0              pyhd3eb1b0_1
isort                     5.9.3              pyhd3eb1b0_0
itsdangerous              2.1.2                    pypi_0    pypi
jaraco-functools          3.5.2                    pypi_0    pypi
jedi                      0.18.1          py310haa95532_1
jellyfish                 0.9.0           py310h2bbff1b_0
jinja2                    3.1.2           py310haa95532_0
jinja2-time               0.2.0              pyhd3eb1b0_3
joblib                    1.2.0                    pypi_0    pypi
jpeg                      9e                   h2bbff1b_0
jsonschema                4.16.0          py310haa95532_0
jupyter_client            7.4.8           py310haa95532_0
jupyter_core              5.1.1           py310haa95532_0
jupyterlab_pygments       0.1.2                      py_0
keyring                   23.4.0          py310haa95532_0
kiwisolver                1.4.4           py310hd77b12b_0
lazy-object-proxy         1.6.0           py310h2bbff1b_0
lerc                      3.0                  hd77b12b_0
libbrotlicommon           1.0.9                h2bbff1b_7
libbrotlidec              1.0.9                h2bbff1b_7
libbrotlienc              1.0.9                h2bbff1b_7
libclang                  12.0.0          default_h627e005_2
libdeflate                1.8                  h2bbff1b_5
libffi                    3.4.2                hd77b12b_6
libiconv                  1.16                 h2bbff1b_2
libogg                    1.3.5                h2bbff1b_1
libpng                    1.6.37               h2a8f88b_0
libsodium                 1.0.18               h62dcd97_0
libspatialindex           1.9.3                h6c2663c_0
libtiff                   4.5.0                h8a3f274_0
libvorbis                 1.3.7                he774522_0
libwebp                   1.2.4                h2bbff1b_0
libwebp-base              1.2.4                h2bbff1b_0
libxml2                   2.9.14               h0ad7f3c_0
libxslt                   1.1.35               h2bbff1b_0
lxml                      4.9.1           py310h1985fb9_0
lz4-c                     1.9.4                h2bbff1b_0
markdown                  3.4.1                    pypi_0    pypi
markdown2                 2.4.7                    pypi_0    pypi
markupsafe                2.1.1           py310h2bbff1b_0
matplotlib                3.6.2           py310haa95532_0
matplotlib-base           3.6.2           py310h1094b8e_0
matplotlib-inline         0.1.6           py310haa95532_0
mccabe                    0.7.0              pyhd3eb1b0_0
mistune                   0.8.4           py310h2bbff1b_1000
mkl                       2021.4.0           haa95532_640
mkl-service               2.4.0           py310h2bbff1b_0
mkl_fft                   1.3.1           py310ha0764ea_0
mkl_random                1.2.2           py310h4ed8f06_0
more-itertools            9.0.0                    pypi_0    pypi
multitasking              0.0.11                   pypi_0    pypi
munkres                   1.1.4                      py_0
mypy_extensions           0.4.3           py310haa95532_1
nbclient                  0.5.13          py310haa95532_0
nbconvert                 6.5.4           py310haa95532_0
nbformat                  5.7.0           py310haa95532_0
nest-asyncio              1.5.6           py310haa95532_0
numexpr                   2.8.4           py310hd213c9f_0
numpy                     1.23.5          py310h60c9a35_0
numpy-base                1.23.5          py310h04254f7_0
numpydoc                  1.5.0           py310haa95532_0
opencv-python             4.7.0.72                 pypi_0    pypi
openpyxl                  3.1.1                    pypi_0    pypi
openssl                   1.1.1s               h2bbff1b_0
orgparse                  0.3.2                    pypi_0    pypi
packaging                 22.0            py310haa95532_0
pandas                    1.5.2           py310h4ed8f06_0
pandocfilters             1.5.0              pyhd3eb1b0_0
paramiko                  2.8.1              pyhd3eb1b0_0
parso                     0.8.3              pyhd3eb1b0_0
pathspec                  0.9.0           py310haa95532_0
pbr                       5.11.1                   pypi_0    pypi
pcre                      8.45                 hd77b12b_0
pdfminer-six              20221105                 pypi_0    pypi
pexpect                   4.8.0              pyhd3eb1b0_3
pickleshare               0.7.5           pyhd3eb1b0_1003
pillow                    9.3.0           py310hdc2b20a_1
pip                       22.3.1          py310haa95532_0
platformdirs              2.5.2           py310haa95532_0
pluggy                    1.0.0           py310haa95532_1
ply                       3.11            py310haa95532_0
poyo                      0.5.0              pyhd3eb1b0_0
prompt-toolkit            3.0.36          py310haa95532_0
protobuf                  3.20.3                   pypi_0    pypi
psutil                    5.9.0           py310h2bbff1b_0
ptyprocess                0.7.0              pyhd3eb1b0_2
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycodestyle               2.8.0              pyhd3eb1b0_0
pycparser                 2.21               pyhd3eb1b0_0
pydocstyle                6.1.1              pyhd3eb1b0_0
pyflakes                  2.4.0              pyhd3eb1b0_0
pygments                  2.11.2             pyhd3eb1b0_0
pylint                    2.14.5          py310haa95532_0
pyls-spyder               0.4.0              pyhd3eb1b0_0
pynacl                    1.5.0           py310h8cc25b3_0
pyopenssl                 22.0.0             pyhd3eb1b0_0
pyparsing                 3.0.9           py310haa95532_0
pypdf                     3.5.1                    pypi_0    pypi
pypdf2                    2.12.1                   pypi_0    pypi
pyqt                      5.15.7          py310hd77b12b_0
pyqt5-sip                 12.11.0         py310hd77b12b_0
pyqtwebengine             5.15.7          py310hd77b12b_0
pyrsistent                0.18.0          py310h2bbff1b_0
pysocks                   1.7.1           py310haa95532_0
pytest                    7.2.1                    pypi_0    pypi
python                    3.10.9               h966fe2a_0
python-dateutil           2.8.2              pyhd3eb1b0_0
python-fastjsonschema     2.16.2          py310haa95532_0
python-lsp-black          1.2.1           py310haa95532_0
python-lsp-jsonrpc        1.0.0              pyhd3eb1b0_0
python-lsp-server         1.5.0           py310haa95532_0
python-slugify            5.0.2              pyhd3eb1b0_0
pytz                      2022.7          py310haa95532_0
pywin32                   305             py310h2bbff1b_0
pywin32-ctypes            0.2.0           py310haa95532_1000
pyyaml                    6.0             py310h2bbff1b_1
pyzmq                     23.2.0          py310hd77b12b_0
qdarkstyle                3.0.2              pyhd3eb1b0_0
qstylizer                 0.2.2                    pypi_0    pypi
qt-main                   5.15.2               he8e5bd7_7
qt-webengine              5.15.9               hb9a9bb5_5
qtawesome                 1.2.2                    pypi_0    pypi
qtconsole                 5.3.2           py310haa95532_0
qtpy                      2.2.0           py310haa95532_0
qtwebkit                  5.212                h3ad3cdb_4
requests                  2.28.1          py310haa95532_0
rope                      0.22.0             pyhd3eb1b0_0
rsa                       4.9                      pypi_0    pypi
rtree                     0.9.7           py310h2eaa2aa_1
scikit-learn              1.2.1                    pypi_0    pypi
scipy                     1.10.0                   pypi_0    pypi
seaborn                   0.12.2          py310haa95532_0
setuptools                65.6.3          py310haa95532_0
simplejson                3.18.1                   pypi_0    pypi
sip                       6.6.2           py310hd77b12b_0
six                       1.16.0             pyhd3eb1b0_1
smart-importer            0.4                      pypi_0    pypi
snowballstemmer           2.2.0              pyhd3eb1b0_0
sortedcontainers          2.4.0              pyhd3eb1b0_0
soupsieve                 2.3.2.post1     py310haa95532_0
sphinx                    5.0.2           py310haa95532_0
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0
sphinxcontrib-htmlhelp    2.0.0              pyhd3eb1b0_0
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0
sphinxcontrib-serializinghtml 1.1.5              pyhd3eb1b0_0
spyder                    5.3.3           py310haa95532_0
spyder-kernels            2.3.3           py310haa95532_0
sqlalchemy                0.7.10                   pypi_0    pypi
sqlalchemy-migrate        0.11.0                   pypi_0    pypi
sqlite                    3.40.1               h2bbff1b_0
sqlparse                  0.4.3                    pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
tempita                   0.5.2                    pypi_0    pypi
text-unidecode            1.3                pyhd3eb1b0_0
textdistance              4.2.1              pyhd3eb1b0_0
threadpoolctl             3.1.0                    pypi_0    pypi
three-merge               0.1.1              pyhd3eb1b0_0
tinycss2                  1.2.1           py310haa95532_0
tk                        8.6.12               h2bbff1b_0
toml                      0.10.2             pyhd3eb1b0_0
tomli                     2.0.1           py310haa95532_0
tomlkit                   0.11.1          py310haa95532_0
tornado                   6.2             py310h2bbff1b_0
traitlets                 5.7.1           py310haa95532_0
typing_extensions         4.4.0           py310haa95532_0
tzdata                    2022.7                   pypi_0    pypi
ujson                     5.4.0           py310hd77b12b_0
unidecode                 1.2.0              pyhd3eb1b0_0
uritemplate               4.1.1                    pypi_0    pypi
urllib3                   1.26.14         py310haa95532_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
watchdog                  2.1.6           py310haa95532_0
wcwidth                   0.2.5              pyhd3eb1b0_0
webencodings              0.5.1           py310haa95532_1
werkzeug                  2.2.2                    pypi_0    pypi
whatthepatch              1.0.2           py310haa95532_0
wheel                     0.37.1             pyhd3eb1b0_0
win_inet_pton             1.1.0           py310haa95532_0
wincertstore              0.2             py310haa95532_2
wrapt                     1.14.1          py310h2bbff1b_0
xlrd                      0.7.1                    pypi_0    pypi
xlwt                      0.7.2                    pypi_0    pypi
xz                        5.2.10               h8cc25b3_1
yaml                      0.2.5                he774522_0
yapf                      0.31.0             pyhd3eb1b0_0
yfinance                  0.2.9                    pypi_0    pypi
zeromq                    4.3.4                hd77b12b_0
zipp                      3.11.0          py310haa95532_0
zlib                      1.2.13               h8cc25b3_0
zstd                      1.5.2                h19a0ad4_0
```

### pip list

```
(acc) C:\Users\c740\OneDrive\areas\accounting>pip list
Package                       Version
----------------------------- ------------------
alabaster                     0.7.12
appdirs                       1.4.4
arrow                         1.2.3
asgiref                       3.6.0
astroid                       2.11.7
atomicwrites                  1.4.0
attrs                         22.1.0
autopep8                      1.6.0
Babel                         2.11.0
backcall                      0.2.0
bcrypt                        3.2.0
beancount                     2.3.5
beancount-categorizer         0.1.dev12+g9900eaa
beancount-reds-plugins        0.3.0
beangrow                      0.0.0
beautifulsoup4                4.11.1
binaryornot                   0.4.4
black                         22.6.0
bleach                        4.1.0
bottle                        0.12.23
Bottleneck                    1.3.5
brotlipy                      0.7.0
bs4                           0.0.1
cachetools                    5.3.0
camelot-py                    0.9.0
certifi                       2022.12.7
cffi                          1.15.1
chardet                       4.0.0
charset-normalizer            2.0.4
cheroot                       8.6.0
click                         8.0.4
click-aliases                 1.0.1
cloudpickle                   2.0.0
colorama                      0.4.6
comm                          0.1.2
contourpy                     1.0.5
cookiecutter                  1.7.3
cryptography                  38.0.4
cycler                        0.11.0
debugpy                       1.5.1
decorator                     5.1.1
defusedxml                    0.7.1
diff-match-patch              20200713
dill                          0.3.6
Django                        4.1.7
docutils                      0.18.1
Elixir                        0.7.1
entrypoints                   0.4
et-xmlfile                    1.1.0
exceptiongroup                1.1.0
fastjsonschema                2.16.2
fava                          1.23.1
fava-income-reports           0.1.dev13+g8557507
fava-investor                 0.5.0
fava-portfolio-returns        0.1.dev10+g2621ef7
flake8                        4.0.1
Flask                         2.2.2
Flask-Babel                   2.0.0
flit_core                     3.6.0
fonttools                     4.25.0
frozendict                    2.3.4
google-api-core               2.11.0
google-api-python-client      2.74.0
google-auth                   2.16.0
google-auth-httplib2          0.1.0
googleapis-common-protos      1.58.0
html5lib                      1.1
httplib2                      0.21.0
idna                          3.4
imagesize                     1.4.1
importlib-metadata            4.11.3
inflection                    0.5.1
iniconfig                     2.0.0
intervaltree                  3.1.0
ipykernel                     6.19.2
ipython                       7.31.1
ipython-genutils              0.2.0
isort                         5.9.3
itsdangerous                  2.1.2
jaraco.functools              3.5.2
jedi                          0.18.1
jellyfish                     0.9.0
Jinja2                        3.1.2
jinja2-time                   0.2.0
joblib                        1.2.0
jsonschema                    4.16.0
jupyter_client                7.4.8
jupyter_core                  5.1.1
jupyterlab-pygments           0.1.2
keyring                       23.4.0
kiwisolver                    1.4.4
lazy-object-proxy             1.6.0
lxml                          4.9.1
Markdown                      3.4.1
markdown2                     2.4.7
MarkupSafe                    2.1.1
matplotlib                    3.6.2
matplotlib-inline             0.1.6
mccabe                        0.7.0
mistune                       0.8.4
mkl-fft                       1.3.1
mkl-random                    1.2.2
mkl-service                   2.4.0
more-itertools                9.0.0
multitasking                  0.0.11
munkres                       1.1.4
mypy-extensions               0.4.3
nbclient                      0.5.13
nbconvert                     6.5.4
nbformat                      5.7.0
nest-asyncio                  1.5.6
numexpr                       2.8.4
numpy                         1.23.5
numpydoc                      1.5.0
opencv-python                 4.7.0.72
openpyxl                      3.1.1
orgparse                      0.3.2
packaging                     22.0
pandas                        1.5.2
pandocfilters                 1.5.0
paramiko                      2.8.1
parso                         0.8.3
pathspec                      0.9.0
pbr                           5.11.1
pdfminer.six                  20221105
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        9.3.0
pip                           22.3.1
platformdirs                  2.5.2
pluggy                        1.0.0
ply                           3.11
poyo                          0.5.0
prompt-toolkit                3.0.36
protobuf                      3.20.3
psutil                        5.9.0
ptyprocess                    0.7.0
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pycodestyle                   2.8.0
pycparser                     2.21
pydocstyle                    6.1.1
pyflakes                      2.4.0
Pygments                      2.11.2
pylint                        2.14.5
pyls-spyder                   0.4.0
PyNaCl                        1.5.0
pyOpenSSL                     22.0.0
pyparsing                     3.0.9
pypdf                         3.5.1
PyPDF2                        2.12.1
PyQt5                         5.15.7
PyQt5-sip                     12.11.0
PyQtWebEngine                 5.15.4
pyrsistent                    0.18.0
PySocks                       1.7.1
pytest                        7.2.1
python-dateutil               2.8.2
python-lsp-black              1.2.1
python-lsp-jsonrpc            1.0.0
python-lsp-server             1.5.0
python-slugify                5.0.2
pytz                          2022.7
pywin32                       305.1
pywin32-ctypes                0.2.0
PyYAML                        6.0
pyzmq                         23.2.0
QDarkStyle                    3.0.2
qstylizer                     0.2.2
QtAwesome                     1.2.2
qtconsole                     5.3.2
QtPy                          2.2.0
requests                      2.28.1
rope                          0.22.0
rsa                           4.9
Rtree                         0.9.7
scikit-learn                  1.2.1
scipy                         1.10.0
seaborn                       0.12.2
setuptools                    65.6.3
simplejson                    3.18.1
sip                           6.6.2
six                           1.16.0
smart-importer                0.4
snowballstemmer               2.2.0
sortedcontainers              2.4.0
soupsieve                     2.3.2.post1
Sphinx                        5.0.2
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
spyder                        5.3.3
spyder-kernels                2.3.3
SQLAlchemy                    0.7.10
sqlalchemy-migrate            0.11.0
sqlparse                      0.4.3
tabulate                      0.9.0
Tempita                       0.5.2
text-unidecode                1.3
textdistance                  4.2.1
threadpoolctl                 3.1.0
three-merge                   0.1.1
tinycss2                      1.2.1
toml                          0.10.2
tomli                         2.0.1
tomlkit                       0.11.1
tornado                       6.2
traitlets                     5.7.1
typing_extensions             4.4.0
tzdata                        2022.7
ujson                         5.4.0
Unidecode                     1.2.0
uritemplate                   4.1.1
urllib3                       1.26.14
watchdog                      2.1.6
wcwidth                       0.2.5
webencodings                  0.5.1
Werkzeug                      2.2.2
whatthepatch                  1.0.2
wheel                         0.37.1
win-inet-pton                 1.1.0
wincertstore                  0.2
wrapt                         1.14.1
xlrd                          0.7.1
xlwt                          0.7.2
yapf                          0.31.0
yfinance                      0.2.9
zipp                          3.11.0

```

**Comment by yagebu** [comment]
The error message says that your input file contains some bytes that aren't valid UTF8 - Fava only supports input files that are UTF8 so the error is expected in that case

**Comment by erpreciso** [comment]
Thanks. Trying to reproduce the issue, and copying and pasting the example above into a test ledger in my production environment, allows the editor to works correctly, regardless of the characters (see screenshot).

I suspect the importer I am using does not return a UTF8-encoded file. I'll review the importer.

<img width="826" alt="image" src="https://github.com/beancount/fava/assets/6203009/fa0325d2-ffae-417c-8143-310f77fbd8bd">
