### ISSUE TITLE
Budgets in `main`: Fava crashing in template render.

### ISSUE THREAD

**Issue by muonzoo** [beancount/fava#1611]
## Description

When attempting to render the monthly changes in expenses with the budget enabled; fava crashes while attempting to render the template. Something about commit b8257c996dd78389 is responsible for this (I used `git bisect` to hunt this down using the `contrib/examples/budgets-example.beancount` and a minimal environment. )

The commit is rather 'large' so I didn't dig in myself.

`v1.24.4` works fine: loading https://fava.pythonanywhere.com/example-with-budgets/account/Expenses/changes/ or the locally hosted version produces the expected chart with budget figures:

<img width="576" alt="Screenshot 2023-05-16 at 09 20 24" src="https://github.com/beancount/fava/assets/77228/41fdc69e-ca56-40d3-8bed-0d3395d70408">

When I move to the next commit [b8257c9](https://github.com/beancount/fava/commit/b8257c996dd78389a471fd4e5714d956c7a017da) I get the internal crash on `hasattr()` while rendering the same URL:

## Traceback
```
 Exception on /example-with-budgets/account/Expenses/changes/ [GET]                                             ─╯
Traceback (most recent call last):
  File "/Users/alan/.pyenv/versions/3.11.1/envs/fava/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alan/.pyenv/versions/3.11.1/envs/fava/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alan/.pyenv/versions/3.11.1/envs/fava/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alan/.pyenv/versions/3.11.1/envs/fava/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alan/Documents/scm/gh/fava/src/fava/application.py", line 313, in account
    return render_template(
           ^^^^^^^^^^^^^^^^
  File "/Users/alan/.pyenv/versions/3.11.1/envs/fava/lib/python3.11/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alan/.pyenv/versions/3.11.1/envs/fava/lib/python3.11/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alan/.pyenv/versions/3.11.1/envs/fava/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/alan/.pyenv/versions/3.11.1/envs/fava/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/alan/Documents/scm/gh/fava/src/fava/templates/account.html", line 8, in top-level template code
    {% set journal = subreport == 'journal' %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alan/Documents/scm/gh/fava/src/fava/templates/_layout.html", line 31, in top-level template code
    {% block content %}
  File "/Users/alan/Documents/scm/gh/fava/src/fava/templates/account.html", line 40, in block 'content'
    {{ tree_table.account_tree(account_name, interval_balances, dates, accumulate) }}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alan/.pyenv/versions/3.11.1/envs/fava/lib/python3.11/site-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alan/Documents/scm/gh/fava/src/fava/templates/_tree_table.html", line 102, in template
    {% for account in [interval_balances[0].get(account_name)] recursive %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alan/Documents/scm/gh/fava/src/fava/templates/_tree_table.html", line 136, in template
    {% for currency, number in budget_children.items() if currency not in balance_children.currencies() %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alan/Documents/scm/gh/fava/src/fava/templates/_tree_table.html", line 136, in template
    {% for currency, number in budget_children.items() if currency not in balance_children.currencies() %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alan/.pyenv/versions/3.11.1/envs/fava/lib/python3.11/site-packages/jinja2/utils.py", line 83, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

## Environment

OS: macos 22.4.0 Darwin Kernel Version 22.4.0
Python : 3.11.1 (managed under pyenv)
Fava:  Commit b8257c996dd78389 

## Reproduce error:

```
pyenv virtualenv 3.11 fava
pyenv activate fava
# inside fava directory:
git co b8257c9
make clean && make && pip install -e .
fava --port 12345 contrib/examples/budgets-example.beancount
```

To confirm, you can test with `v1.24.4`  without issues:

```
git co v.1.24.4
make clean && make && pip install -e .
fava --port 12345 contrib/examples/budgets-example.beancount
```
Navigate to [http://127.0.0.1:12345/example-with-budgets/account/Expenses/changes/](http://127.0.0.1:12345/example-with-budgets/account/Expenses/changes/)

See that things render similarly to the screenshot in this bug.

## Package List
```
Babel==2.12.1
beancount==2.3.5
beautifulsoup4==4.12.2
blinker==1.6.2
bottle==0.12.25
cachetools==5.3.0
certifi==2023.5.7
chardet==5.1.0
charset-normalizer==3.1.0
cheroot==9.0.0
click==8.1.3
colorama==0.4.6
distlib==0.3.6
fava==1.24.4
filelock==3.12.0
Flask==2.3.2
flask-babel==3.1.0
google-api-core==2.11.0
google-api-python-client==2.86.0
google-auth==2.18.0
google-auth-httplib2==0.1.0
googleapis-common-protos==1.59.0
httplib2==0.22.0
idna==3.4
iniconfig==2.0.0
itsdangerous==2.1.2
jaraco.functools==3.6.0
Jinja2==3.1.2
lxml==4.9.2
markdown2==2.4.8
MarkupSafe==2.1.2
more-itertools==9.1.0
packaging==23.1
pip==23.1.2
platformdirs==3.5.1
pluggy==1.0.0
ply==3.11
protobuf==4.23.0
pyasn1==0.5.0
pyasn1-modules==0.3.0
pyparsing==3.0.9
pyproject_api==1.5.1
pytest==7.3.1
python-dateutil==2.8.2
python-magic==0.4.27
pytz==2023.3
requests==2.30.0
rsa==4.9
setuptools==65.5.0
simplejson==3.19.1
six==1.16.0
soupsieve==2.4.1
tox==4.5.1
uritemplate==4.1.1
urllib3==1.26.15
virtualenv==20.23.0
Werkzeug==2.3.4
```

**Comment by yagebu** [comment]
Thanks for the report :)

**Comment by muonzoo** [comment]
Thanks for the quick fix. I'm embarrassed that it was so straight-forward. I should have at least taken a glance. :-) THanks for the fix! Back to the tip!
