### ISSUE TITLE
Loading entry context fails for custom directives

### ISSUE THREAD

**Issue by pwalkr** [beancount/fava#1820]
In Journal view, clicking the date to see context of custom directives fails:
![snip-2024-06-03_87784](https://github.com/beancount/fava/assets/1776604/f1808efc-1606-408f-a25b-cf32275d3c1c)

It returns `Loading entry context failed...` in the browser with the full console stack trace below. This broke in `v1.21` - if I try on `v1.20`, I can see the context window for custom options:
![snip-2024-06-02_87077](https://github.com/beancount/fava/assets/1776604/e8ffde08-1e1a-4fb5-8a83-2787903e6680)

Full console stack trace (from `1.27.2` in docker)
```
Exception on /walker/api/context [GET]
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/app/lib/python3.9/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/app/lib/python3.9/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/lib/python3.9/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/lib/python3.9/site-packages/fava/json_api.py", line 159, in _wrapper
    return json_success(res)
  File "/app/lib/python3.9/site-packages/fava/json_api.py", line 66, in json_success
    return jsonify(
  File "/app/lib/python3.9/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
  File "/app/lib/python3.9/site-packages/flask/json/provider.py", line 105, in response
    return self._app.response_class(self.dumps(obj), mimetype="application/json")
  File "/app/lib/python3.9/site-packages/fava/core/charts.py", line 86, in dumps
    return dumps(obj)
  File "/app/lib/python3.9/site-packages/fava/core/charts.py", line 69, in dumps
    return simplejson_dumps(
  File "/app/lib/python3.9/site-packages/simplejson/__init__.py", line 381, in dumps
    return cls(
  File "/app/lib/python3.9/site-packages/simplejson/encoder.py", line 300, in encode
    chunks = list(chunks)
  File "/app/lib/python3.9/site-packages/simplejson/encoder.py", line 714, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/app/lib/python3.9/site-packages/simplejson/encoder.py", line 668, in _iterencode_dict
    for chunk in chunks:
  File "/app/lib/python3.9/site-packages/simplejson/encoder.py", line 735, in _iterencode
    for chunk in _iterencode(o, _current_indent_level):
  File "/app/lib/python3.9/site-packages/simplejson/encoder.py", line 714, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/app/lib/python3.9/site-packages/simplejson/encoder.py", line 668, in _iterencode_dict
    for chunk in chunks:
  File "/app/lib/python3.9/site-packages/simplejson/encoder.py", line 668, in _iterencode_dict
    for chunk in chunks:
  File "/app/lib/python3.9/site-packages/simplejson/encoder.py", line 544, in _iterencode_list
    for chunk in chunks:
  File "/app/lib/python3.9/site-packages/simplejson/encoder.py", line 668, in _iterencode_dict
    for chunk in chunks:
  File "/app/lib/python3.9/site-packages/simplejson/encoder.py", line 734, in _iterencode
    o = _default(o)
  File "/app/lib/python3.9/site-packages/fava/core/charts.py", line 64, in _json_default
    raise TypeError
TypeError
```

FWIW, I've found the `insert-entry` options to be great anchor points in the ledger for my accounts, especially since discovering they show up in the filtered journal if you use an unquoted account (with link, as shown in first screenshot)
```
2021-06-01 custom "fava-option" "insert-entry" Assets:Bank
```

**Comment by egetzner** [comment]
Interestingly, I get a very similar error/stack trace now with fava 1.30 when opening the Import page:

```Exception on /beancount/api/imports [GET]
Traceback (most recent call last):
  File "/home/egetzner/beancount-fava-1.30/.venv/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/egetzner/beancount-fava-1.30/.venv/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/egetzner/beancount-fava-1.30/.venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/egetzner/beancount-fava-1.30/.venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/egetzner/beancount-fava-1.30/.venv/lib/python3.13/site-packages/fava/json_api.py", line 262, in _wrapper
    return json_success(res)
  File "/home/egetzner/beancount-fava-1.30/.venv/lib/python3.13/site-packages/fava/json_api.py", line 94, in json_success
    return jsonify(
        {"data": data, "mtime": str(g.ledger.mtime)},
    )
  File "/home/egetzner/beancount-fava-1.30/.venv/lib/python3.13/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/egetzner/beancount-fava-1.30/.venv/lib/python3.13/site-packages/flask/json/provider.py", line 105, in response
    return self._app.response_class(self.dumps(obj), mimetype="application/json")
                                    ~~~~~~~~~~^^^^^
  File "/home/egetzner/beancount-fava-1.30/.venv/lib/python3.13/site-packages/fava/core/charts.py", line 83, in dumps
    return dumps(obj)
  File "/home/egetzner/beancount-fava-1.30/.venv/lib/python3.13/site-packages/fava/core/charts.py", line 66, in dumps
    return simplejson_dumps(
        obj,
    ...<2 lines>...
        default=_json_default,
    )
  File "/home/egetzner/beancount-fava-1.30/.venv/lib/python3.13/site-packages/simplejson/__init__.py", line 395, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "/home/egetzner/beancount-fava-1.30/.venv/lib/python3.13/site-packages/simplejson/encoder.py", line 300, in encode
    chunks = list(chunks)
  File "/home/egetzner/beancount-fava-1.30/.venv/lib/python3.13/site-packages/simplejson/encoder.py", line 714, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
                 ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/egetzner/beancount-fava-1.30/.venv/lib/python3.13/site-packages/simplejson/encoder.py", line 668, in _iterencode_dict
    for chunk in chunks:
                 ^^^^^^
  File "/home/egetzner/beancount-fava-1.30/.venv/lib/python3.13/site-packages/simplejson/encoder.py", line 544, in _iterencode_list
    for chunk in chunks:
                 ^^^^^^
  File "/home/egetzner/beancount-fava-1.30/.venv/lib/python3.13/site-packages/simplejson/encoder.py", line 735, in _iterencode
    for chunk in _iterencode(o, _current_indent_level):
                 ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/egetzner/beancount-fava-1.30/.venv/lib/python3.13/site-packages/simplejson/encoder.py", line 714, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
                 ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/egetzner/beancount-fava-1.30/.venv/lib/python3.13/site-packages/simplejson/encoder.py", line 668, in _iterencode_dict
    for chunk in chunks:
                 ^^^^^^
  File "/home/egetzner/beancount-fava-1.30/.venv/lib/python3.13/site-packages/simplejson/encoder.py", line 544, in _iterencode_list
    for chunk in chunks:
                 ^^^^^^
  File "/home/egetzner/beancount-fava-1.30/.venv/lib/python3.13/site-packages/simplejson/encoder.py", line 735, in _iterencode
    for chunk in _iterencode(o, _current_indent_level):
                 ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/egetzner/beancount-fava-1.30/.venv/lib/python3.13/site-packages/simplejson/encoder.py", line 714, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
                 ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/egetzner/beancount-fava-1.30/.venv/lib/python3.13/site-packages/simplejson/encoder.py", line 668, in _iterencode_dict
    for chunk in chunks:
                 ^^^^^^
  File "/home/egetzner/beancount-fava-1.30/.venv/lib/python3.13/site-packages/simplejson/encoder.py", line 734, in _iterencode
    o = _default(o)
  File "/home/egetzner/beancount-fava-1.30/.venv/lib/python3.13/site-packages/fava/core/charts.py", line 61, in _json_default
    raise TypeError  # pragma: no cover
    ^^^^^^^^^^^^^^^
TypeError
```

The importers worked fine with fava 1.29 before, nothing else has changed. As soon as I add any importer, I get this exception. Did you ever find a way around this issue?

**Comment by yagebu** [comment]
@egetzner can you provide some example to reproduce this with and create a new issue?

**Comment by egetzner** [comment]
@yagebu looks the type error resulted from an incorrect importer name resolution for the Importer classes:
In my old ImporterProtocol code, I would override the name method like so:
```
    def name(self):
        return f'{self.IMPORTER_NAME}: ({self.importer_account})'
```
Since the new Importer defines name as a property instead of a method, this didn't fail directly, the name just looked strange in the beangulp identify command:
`  <bound method Importer.name of <shared.erste.Importer object at 0x7be988fb0830>> `

Fava couldn't resolve the name once it tried to print it in the importer page. Changing the name to a property fixed this issue for me.
```
    @property
    def name(self):
        return f'{self.IMPORTER_NAME}: ({self.importer_account})'
```

Thanks for your response!

**Comment by yagebu** [comment]
Good that you got it working - the name method / now property would have been my first guess as well :) I've runtime validations of these types returned by the various methods in #1931 so that others who run into this sort of issue should get a better error message.
