### ISSUE TITLE
Error in journal report due to entry.postings[0].account IndexError

### ISSUE THREAD

**Issue by nathangrigg** [beancount/fava#429]
When viewing the journal report, there are sometimes transactions that have no postings due to the insertion of conversions from [here](https://bitbucket.org/blais/beancount/src/7e4b02ff3b41376c31bc35c65c04d62ea95425cf/src/python/beancount/ops/summarize.py?at=default&fileviewer=file-view-default#summarize.py-489).

For me, this happened when I was selecting a year (e.g. ?time=2016)

The offending template code is [here](https://github.com/beancount/fava/blob/58af3481f81dc5ff29992605bbb0d7e25132e32f/fava/templates/_journal_table.html#L171).

The exception looks like 

```
[2016-12-02 18:31:08,363] ERROR in app: Exception on /nathans-money/journal/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/site-packages/fava/application.py", line 245, in report
    return render_template('{}.html'.format(report_name))
  File "/usr/local/lib/python3.5/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/local/lib/python3.5/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.5/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.5/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/site-packages/fava/templates/journal.html", line 2, in top-level template code
    {% set active_page = 'journal' %}
  File "/usr/local/lib/python3.5/site-packages/fava/templates/_layout.html", line 52, in top-level template code
    {% block content %}{% endblock %}
  File "/usr/local/lib/python3.5/site-packages/fava/templates/journal.html", line 11, in block "content"
    {% include "_journal_table.html" %}
  File "/usr/local/lib/python3.5/site-packages/fava/templates/_journal_table.html", line 170, in top-level template code
    <span class="description{%- if type == 'transaction' %} droptarget{% endif -%}"{%- if type == 'transaction' %} data-filename="{{ entry.meta.filename }}" data-lineno="{{ entry.meta.lineno }}" data-account-name="{{ entry.postings[0].account }}"{% endif -%}>
  File "/usr/local/lib/python3.5/site-packages/jinja2/environment.py", line 408, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: list object has no element 0
```

One possible fix is to replace `entry.postings[0].account` with ` entry.postings[0].account if entry.postings else ""`.

**Comment by yagebu** [comment]
Thank you for the detailed report! I've applied your fix.

@blais: Are transactions without postings something that should occur or could this be considered a bug in the conversions code?

**Comment by blais** [comment]
I think you just found a bug;  the check here:
https://bitbucket.org/blais/beancount/src/7e4b02ff3b41376c31bc35c65c04d62ea95425cf/src/python/beancount/ops/summarize.py?at=default&fileviewer=file-view-default#summarize.py-474
was intended to avoid this, but it's possible for the balance to be
non-empty but the cost to be empty.
I'll fix the bug.

**Comment by blais** [comment]
Fixed: https://bitbucket.org/blais/beancount/commits/6aa789b084bb4ff052f1ca707542ace2fc4bc271

**Comment by blais** [comment]
https://bitbucket.org/blais/beancount/commits/6aa789b084bb4ff052f1ca707542ace2fc4bc271
