### ISSUE TITLE
not possible to install development 

### ISSUE THREAD

**Issue by pfrancois** [beancount/fava#430]
I have problem to install fava dev on a machine.
when i try to launch make build-js, i have errorlog  in npm file attached.

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle fava@0.0.0~prebuild: fava@0.0.0
6 silly lifecycle fava@0.0.0~prebuild: no script for prebuild, continuing
7 info lifecycle fava@0.0.0~build: fava@0.0.0^ 
8 verbose lifecycle fava@0.0.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle fava@0.0.0~build: PATH: /usr/share/npm/bin/node-gyp-bin:/root/fava/fava/static/node_modules/.bin:/root/fava/venv/bin:/root/bin:/root/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin^ 
10 verbose lifecycle fava@0.0.0~build: CWD: /root/fava/fava/static
11 silly lifecycle fava@0.0.0~build: Args: [ '-c', 'rollup -c' ]
12 info lifecycle fava@0.0.0~build: Failed to exec build script
13 verbose stack Error: fava@0.0.0 build: `rollup -c`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
13 verbose stack     at emitTwo (events.js:87:13)
13 verbose stack     at ChildProcess.emit (events.js:172:7)
13 verbose stack     at maybeClose (internal/child_process.js:821:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid fava@0.0.0
15 verbose cwd /root/fava/fava/static
16 error Linux 4.4.0-51-generic
17 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
18 error node v4.2.6
19 error npm  v3.5.2
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error fava@0.0.0 build: `rollup -c`
24 error spawn ENOENT
25 error Failed at the fava@0.0.0 build script 'rollup -c'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the fava package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     rollup -c
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs fava
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls fava
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]
```

how to reproduce the error:
create here https://dply.co/d a free server ubuntu xenial for 2 hours.
connect it with root@ipofserver
then 
run the following lines to install everything
```
apt install mercurial python3-pip python3-lxml
hg clone https://bitbucket.org/blais/beancount
cd beancount
sudo pip3 install .
cd ..

apt install  npm virtualenv
git clone https://github.com/beancount/fava.git
cd fava
virtualenv -p python3 venv
. venv/bin/activate
make build-js
```

i don't really understand why it don't work

**Comment by aumayr** [comment]
Steps to fix this:

```bash
apt install nodejs-legacy
mkdir /root/fava/fava/static/node_modules/node-sass/vendor
cd /root/fava/fava/static
npm rebuild node-sass
cd ../..

# and finally
make build-js
```
