### ISSUE TITLE
Adding transaction fails with INTERNAL_SERVER_ERROR (KeyError: 'metadata')

### ISSUE THREAD

**Issue by ngoonee** [beancount/fava#529]
Just updated to latest commit, this is what I get -

2017-04-17 03:42:15,681 :[2017-04-17 03:42:15,671] ERROR in app: Exception on /bethsimchatadonai-accounts/api/add-transaction/ [PUT]
2017-04-17 03:42:15,683 :Traceback (most recent call last):
2017-04-17 03:42:15,683 :  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1988, in wsgi_app
2017-04-17 03:42:15,683 :    response = self.full_dispatch_request()
2017-04-17 03:42:15,684 :  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1641, in full_dispatch_request
2017-04-17 03:42:15,684 :    rv = self.handle_user_exception(e)
2017-04-17 03:42:15,684 :  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1544, in handle_user_exception
2017-04-17 03:42:15,684 :    reraise(exc_type, exc_value, tb)
2017-04-17 03:42:15,684 :  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
2017-04-17 03:42:15,684 :    raise value
2017-04-17 03:42:15,684 :  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1639, in full_dispatch_request
2017-04-17 03:42:15,684 :    rv = self.dispatch_request()
2017-04-17 03:42:15,684 :  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1625, in dispatch_request
2017-04-17 03:42:15,684 :    return self.view_functions[rule.endpoint](**req.view_args)
2017-04-17 03:42:15,685 :  File "/home/ngoonee/.local/lib/python3.5/site-packages/fava-1.4.dev0-py3.5.egg/fava/json_api.py", line 126, in add_transaction
2017-04-17 03:42:15,685 :    json['metadata'], date, json['flag'], json['payee'],
2017-04-17 03:42:15,685 :KeyError: 'metadata'
2017-04-17 03:42:15,671 :Exception on /bethsimchatadonai-accounts/api/add-transaction/ [PUT]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ngoonee/.local/lib/python3.5/site-packages/fava-1.4.dev0-py3.5.egg/fava/json_api.py", line 126, in add_transaction
    json['metadata'], date, json['flag'], json['payee'],
KeyError: 'metadata'

**Comment by ngoonee** [comment]
Not sure if there's something wrong with the way I'm setting this up, but I don't get this when I install fava+beancount locally. Only on my pythonanywhere install. My update.sh script has this:-

pushd ~/beancount
hg pull
hg up
python3 setup.py build_ext -i
python3 setup.py build
python3 setup.py install --user
popd

pushd ~/fava
git pull
make
python3 setup.py build
python3 setup.py install --user
popd

touch /var/www/ngoonee_pythonanywhere_com_wsgi.py

**Comment by ngoonee** [comment]
Replacing python3 setup.py install --user with pip3 install -e --user ~/fava (and ~/beancount) seems to fix things. I don't know why. Leaving it open for that reason.

**Comment by yagebu** [comment]
The error points to the request not containing the metadata field. I don't really see how that can happen as the Javascript should always make it part of the request. Maybe the frontend code wasn't bundled correctly?

**Comment by ngoonee** [comment]
Unfortunately the symptoms seem correlated (on my pythonanywhere install) with that change from setup.py install to pip3 install -e. Complicating matters is that my own desktop build uses setup.py install (obviously) and works....

**Comment by yagebu** [comment]
Closing this as it's hard to fix it without being able to reproduce it. Feel free to reopen if this occurs in some reproduceable situation.
