### ISSUE TITLE
error 500 when trying to access errors link

### ISSUE THREAD

**Issue by pfrancois** [beancount/fava#535]
when i try to see error in the file (basically going to http://localhost:5000/beancount/errors) withe french translation. 
i have a error 500 below

when i go to the bottom, it seem that there some problem with the translations

```python
 [2017-04-25 00:08:06,165] ERROR in app: Exception on /beancount/errors/ [GET]
Traceback (most recent call last):
  File "/home/francois/.local/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/francois/.local/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/francois/.local/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/francois/.local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/francois/.local/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/francois/.local/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/d/fava/fava/application.py", line 266, in report
    return render_template('{}.html'.format(report_name))
  File "/home/francois/.local/lib/python3.5/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/francois/.local/lib/python3.5/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/mnt/d/fava/fava/templates/errors.html", line 4, in top-level template code
    {% set page_title = _('Errors') %}
  File "/mnt/d/fava/fava/templates/_layout.html", line 52, in top-level template code
    {% block content %}{% endblock %}
  File "/mnt/d/fava/fava/templates/errors.html", line 20, in block "content"
    <td><a class="source" href="{{ link }}" title="{{ _('Show source %(file)s:%(lineno)s', file=error.source['filename'], lineno=error.source['lineno']) }}">{{ error.source['filename'] }}</a></td>
  File "/usr/lib/python3/dist-packages/jinja2/ext.py", line 132, in _gettext_alias
    return __context.call(__context.resolve('gettext'), *args, **kwargs)
  File "/usr/lib/python3/dist-packages/jinja2/ext.py", line 141, in gettext
    return rv % variables
  File "/usr/lib/python3/dist-packages/markupsafe/__init__.py", line 101, in __mod__
    return self.__class__(text_type.__mod__(self, arg))
  File "/usr/lib/python3/dist-packages/markupsafe/__init__.py", line 282, in <lambda>
    __getitem__ = lambda s, x: _MarkupEscapeHelper(s.obj[x], s.escape)
KeyError: 'fichier'
```

**Comment by aumayr** [comment]
This was an error in the translation, which is fixed now and will be released with the next version (due soon):

On poeditor.com the following string was translated wrong:

```Show source %(file)s:%(lineno)s``` was ```Afficher la source %(fichier)s:%(lineno)s```, but should be ```Afficher la source: %(file)s:%(lineno)s```
