### ISSUE TITLE
TagFilter crashes when entry.tags = None

### ISSUE THREAD

**Issue by mhansen** [beancount/fava#552]
Hi folks,

first, thanks for fava. It's an awesome bit of software.

I have some transactions generated through a beancount plugin 'beancount.plugins.unrealized'. These transactions have Transaction.tags = None. Not tags = frozenset().

filters.py crashes on these on line 140:
(entry.tags & self.tags)

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1610, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1831, in preprocess_request
    rv = func()
  File "/Users/mark/src/fava/fava/application.py", line 150, in _perform_global_filters
    g.ledger.filter(**g.filters)
  File "/Users/mark/src/fava/fava/core/__init__.py", line 187, in filter
    self.entries = filter_class.apply(self.entries, self.options)
  File "/Users/mark/src/fava/fava/core/filters.py", line 49, in apply
    return self._filter(entries, options)
  File "/Users/mark/src/fava/fava/core/filters.py", line 35, in _filter
    return [entry for entry in entries if self._include_entry(entry)]
  File "/Users/mark/src/fava/fava/core/filters.py", line 35, in <listcomp>
    return [entry for entry in entries if self._include_entry(entry)]
  File "/Users/mark/src/fava/fava/core/filters.py", line 140, in _include_entry
    (entry.tags & self.tags) or
TypeError: unsupported operand type(s) for &: 'NoneType' and 'set'

Looking at beancount.core.data.Transaction, tags is typed as Optional[Set], which (I think) means it can be None, and we should handle that. Although perhaps there's an argument that it shouldn't be Optional, it should instead default to empty frozenset.

Looks like the error was introduced in a4a3f973a859a6a8a1378b5e530e85814662512c where it changed from `((entry.tags if entry.tags else set()) & self.tags)` to `(entry.tags & self.tags)`. Reverting that should fix it up, I think.

**Comment by yagebu** [comment]
Thanks for the report. There was a change in Beancount a while ago that always forced tags and links to be a set (see the [changelog entry from 2016-12-04](https://bitbucket.org/blais/beancount/src/b278b597befe2dc6ed88e65ab943919c230875b8/CHANGES?at=default&fileviewer=file-view-default#CHANGES-299)). So I'd consider this a bug in the plugin and I'd like to keep the somewhat cleaner code.

**Comment by yagebu** [comment]
@blais: `beancount.plugins.unrealized` shouldn't create Transactions with `None` tags or links [here].(https://bitbucket.org/blais/beancount/src/b278b597befe2dc6ed88e65ab943919c230875b8/beancount/plugins/unrealized.py?at=default&fileviewer=file-view-default#unrealized.py-136)

**Comment by yagebu** [comment]
Created a PR: https://bitbucket.org/blais/beancount/pull-requests/22
