### ISSUE TITLE
Internal Server Error when filtering on a tag

### ISSUE THREAD

**Issue by acatinon** [beancount/fava#569]
Hi,

When I am on the account statment page, if I select a tag in the header, I get a 500 internal server error.

There is the call stack :

```
[2017-07-02 16:41:48,714] ERROR in app: Exception on /beancount/income_statement/ [GET]
Traceback (most recent call last):
  File "/home/aurel/Dev/Bazaar/fava/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/aurel/Dev/Bazaar/fava/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/aurel/Dev/Bazaar/fava/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aurel/Dev/Bazaar/fava/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/aurel/Dev/Bazaar/fava/venv/lib/python3.6/site-packages/flask/app.py", line 1610, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/aurel/Dev/Bazaar/fava/venv/lib/python3.6/site-packages/flask/app.py", line 1831, in preprocess_request
    rv = func()
  File "/home/aurel/Dev/Bazaar/fava/fava/application.py", line 151, in _perform_global_filters
    g.ledger.filter(**g.filters)
  File "/home/aurel/Dev/Bazaar/fava/fava/core/__init__.py", line 186, in filter
    self.entries = filter_class.apply(self.entries, self.options)
  File "/home/aurel/Dev/Bazaar/fava/fava/core/filters.py", line 49, in apply
    return self._filter(entries, options)
  File "/home/aurel/Dev/Bazaar/fava/fava/core/filters.py", line 35, in _filter
    return [entry for entry in entries if self._include_entry(entry)]
  File "/home/aurel/Dev/Bazaar/fava/fava/core/filters.py", line 35, in <listcomp>
    return [entry for entry in entries if self._include_entry(entry)]
  File "/home/aurel/Dev/Bazaar/fava/fava/core/filters.py", line 150, in _include_entry
    ) if self.tags else True
TypeError: unsupported operand type(s) for &: 'NoneType' and 'set'
127.0.0.1 - - [02/Jul/2017 16:41:48] "GET /beancount/income_statement/?tag=%23salaire%2C+&partial=true HTTP/1.1" 500 -
```

I am on the latest sources from the repo.

**Comment by acatinon** [comment]
Aww sorry I just saw the #552 issue... Closing.

**Comment by yagebu** [comment]
Just to clarify - this is also caused by the `beancount.plugins.unrealized` plugin in your case?

**Comment by acatinon** [comment]
Yes absolutely, when I disable the plug in, it work fine.

**Comment by yagebu** [comment]
Ok. This is fixed now in upstream Beancount so once there's a new release of Beancount (or if you install from source), this should work again.
