### ISSUE TITLE
Dependency issue - stack trace on first access to localhost:5000

### ISSUE THREAD

**Issue by jbarlow83** [beancount/fava#590]
```
fava anyfile.beancount
```

It doesn't seem to matter what's in the file.

I created a fresh virtual environment instead of my system one, and that worked, so I have a resolution. Still, it seems there may be some underspecified or conflicting dependency that should be tightened to make it less likely anyone else runs into this.

Both have environments have beancount 2.0rc2, fava 1.5, Flask 0.12.2, and Jinja2 2.9.6.

<details>

```
 * Running on http://localhost:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [18/Sep/2017 23:54:19] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [18/Sep/2017 23:54:19] "GET /business-ledger/ HTTP/1.1" 302 -
[2017-09-18 23:54:20,035] ERROR in app: Exception on /business-ledger/income_statement/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/fava/application.py", line 264, in report
    return render_template('{}.html'.format(report_name))
  File "/usr/local/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/local/lib/python3.6/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/fava/templates/income_statement.html", line 3, in top-level template code
    {% import '_tree_table.html' as tree_table with context %}
  File "/usr/local/lib/python3.6/site-packages/fava/templates/_layout.html", line 43, in top-level template code
    {% block content %}{% endblock %}
  File "/usr/local/lib/python3.6/site-packages/fava/templates/income_statement.html", line 8, in block "content"
    {{ charts.interval_totals(interval, (ledger.options['name_income'], ledger.options['name_expenses']), label=_('Net Profit')) }}
  File "/usr/local/lib/python3.6/site-packages/jinja2/runtime.py", line 553, in _invoke
    rv = self._func(*arguments)
  File "/usr/local/lib/python3.6/site-packages/fava/templates/_charts.html", line 15, in template
    {% do chart_data.append({
  File "/usr/local/lib/python3.6/site-packages/fava/util/__init__.py", line 27, in wrapper
    return list(func(*args, **kwargs))
  File "/usr/local/lib/python3.6/site-packages/fava/core/charts.py", line 106, in interval_totals
    'totals': _inventory_cost_or_value(inventory, end),
  File "/usr/local/lib/python3.6/site-packages/fava/core/charts.py", line 49, in _inventory_cost_or_value
    inventory = cost_or_value(inventory, date)
  File "/usr/local/lib/python3.6/site-packages/fava/template_filters.py", line 41, in cost_or_value
    return inventory.reduce(convert.get_cost)
AttributeError: 'Inventory' object has no attribute 'reduce'
127.0.0.1 - - [18/Sep/2017 23:54:20] "GET /business-ledger/income_statement/ HTTP/1.1" 500 -
```

</details>

**Comment by yagebu** [comment]
Hey, thanks for the report! This looks like an issue with your Beancount installation. The `Inventory.reduce` method was added in 2.0b15 (or before), which is the version that Fava depends on. Do you maybe have an outdated Beancount version installed system-wide? You could try the following in the Python shell to see where your Beancount installation lives:

    import beancount
    beancount.__file__

**Comment by jbarlow83** [comment]
It turned out that I had two different beancount.dist-info directories:

```
drwxr-xr-x   19 jb  staff   646B  5 Jun 15:59 beancount
drwxr-xr-x    9 jb  staff   306B  5 Jun 15:59 beancount-2.0b13.dist-info
drwxr-xr-x    8 jb  staff   272B  5 Jun 15:59 beancount-2.0rc1.dist-info
```

This is against spec and it causes unpredictable results with `pip` and the other packaging tools. In particular it makes`pip` to incorrect report the installed version as `2.0rc1` even though "beancount" actually contained `2.0b13`, evinced by the absence of `Inventory.reduce`. Thanks for pointing that out, as I otherwise wouldn't have known what to look for.

There's some open bugs with PyPA that can cause this situation. It's probably the result of a failed `pip install` at some point.
