### ISSUE TITLE
cryptic TypeError when viewing some accounts due plugins

### ISSUE THREAD

**Issue by Akuukis** [beancount/fava#599]
Browser shows:
```
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```
Server logs has:
```
ERROR in app: Exception on /MyBookABC/account/Assets:MyAccountXYZ/ [GET]
Traceback (most recent call last):
  File "/home/fava/.local/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fava/.local/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fava/.local/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fava/.local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/fava/.local/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fava/.local/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/dist-packages/fava/application.py", line 230, in account
    'account.html', account_name=name, subreport=subreport)
  File "/home/fava/.local/lib/python3.5/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/fava/.local/lib/python3.5/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/fava/.local/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/fava/.local/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fava/.local/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/fava/templates/account.html", line 10, in top-level template code
    {% set journal = subreport == 'journal' %}
  File "/usr/local/lib/python3.5/dist-packages/fava/templates/_layout.html", line 43, in top-level template code
    {% block content %}{% endblock %}
  File "/usr/local/lib/python3.5/dist-packages/fava/templates/account.html", line 31, in block "content"
    {% include "_journal_table.html" %}
  File "/usr/local/lib/python3.5/dist-packages/fava/templates/_journal_table.html", line 156, in top-level template code
    {{ render_tags_links(entry) }}
  File "/home/fava/.local/lib/python3.5/site-packages/jinja2/runtime.py", line 553, in _invoke
    rv = self._func(*arguments)
  File "/usr/local/lib/python3.5/dist-packages/fava/templates/_journal_table.html", line 86, in template
    {% for link_ in entry.links %}
TypeError: 'NoneType' object is not iterable
```

I use plugins `beancount-oneliner` and `beancount-interpolate`, therefore I suspect that they could malform some of transactions and confuse FAVA. I don't know which side to blame, but in both cases I would appreciate some guidance how and where to start debugging this.

**Comment by yagebu** [comment]
The links and tags attribute of a Transaction and Document need to be either a set() or a frozenset() and aren't allowed to be None.  See the changelog entry for Beancount from 2016-12-04:

>  Made .tags and .links attributes of b.data.Transaction and b.data.Document
    directives ensured to always be a set when they're empty. If there are no
    tags (or links), those attributes are set to b.data.EMPTY_SET, whose value
    is a frozenset(). This should make the processing of those attributes a bit
    simpler.
>
>  Note that if you create transactions from plugins and their tags and/or
    links attributes are set None, they will now fail. The right thing to do is
    to set their value to an empty set, or reuse the immutable
    beancount.core.data.EMPTY_SET object.

**Comment by Akuukis** [comment]
@yagebu thank you for pinpointing the cause! I updated plugin and everything works now.
