### ISSUE TITLE
Internal server error on holdings page: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by tbm** [beancount/fava#686]
```
  File "/usr/local/lib/python3.5/dist-packages/fava/templates/holdings.html", line 58, in block "content"
    {{ querytable.querytable(result_types, result_rows, filter_empty=units_column.get(aggregation_key, 1)) }}
  File "/usr/local/lib/python3.5/dist-packages/jinja2/runtime.py", line 579, in _invoke
    rv = self._func(*arguments)
  File "/usr/local/lib/python3.5/dist-packages/fava/templates/_query_table.html", line 46, in template
    {% for name, type in types %}
TypeError: 'NoneType' object is not iterable
```

This is triggered by an account which has a holding at cost.  And one without cost. (I forgot to convert from ledger's @@ 25.61 GBP to {{25.61 GBP}}).

In any case, Fava shouldn't crash.

Test case:

```2010-01-01 open Assets:Pension:NEST
2010-01-01 open Equity:Opening-Balance

2018-01-01 * "Opening balance: NEST"
  Assets:Pension:NEST                                      57.62 GBP
  Equity:Opening-Balance

2018-01-01 * "Opening balance: NEST Higher Risk Fund"
  fund: "NESTHIGHER"
  Assets:Pension:NEST              11.7230 NESTHIGHER {{25.61 GBP, 2017-12-14}}
  Equity:Opening-Balance

2018-01-02 * "NEST: Bought NEST Higher Risk Fund with December employee contributions"
  fund: "NESTHIGHER"
  Assets:Pension:NEST              11.7520 NESTHIGHER @@ 25.61 GBP
  Assets:Pension:NEST                                   -25.61 GBP
```

**Comment by yagebu** [comment]
Can you run the corresponding query in bean-query?

**Comment by tbm** [comment]
```
beancount> SELECT account, units(sum(position)) as units, cost_number as cost, first(getprice(currency, cost_currency)) as price, cost(sum(position)) as book_value, value(sum(position)) as market_value, cost_date as acquisition_date WHERE account_sortkey(account) ~ "^[01]" GROUP BY account, cost_date, currency, cost_currency, cost_number, account_sortkey(account) ORDER BY account_sortkey(account), currency, cost_date
Traceback (most recent call last):
  File "/usr/lib/python3.5/cmd.py", line 214, in onecmd
    func = getattr(self, 'do_' + cmd)
AttributeError: 'BQLShell' object has no attribute 'do_SELECT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/beancount-2.0rc1-py3.5-linux-x86_64.egg/beancount/query/shell.py", line 266, in run_parser
    self.dispatch(statement)
  File "/usr/local/lib/python3.5/dist-packages/beancount-2.0rc1-py3.5-linux-x86_64.egg/beancount/query/shell.py", line 246, in dispatch
    return method(statement)
  File "/usr/local/lib/python3.5/dist-packages/beancount-2.0rc1-py3.5-linux-x86_64.egg/beancount/query/shell.py", line 414, in on_Select
    self.options_map)
  File "/usr/local/lib/python3.5/dist-packages/beancount-2.0rc1-py3.5-linux-x86_64.egg/beancount/query/query_execute.py", line 328, in execute_query
    reverse=(query.ordering == 'DESC'))
TypeError: unorderable types: datetime.date() < NoneType()
beancount> 
```

**Comment by yagebu** [comment]
This seems to be a bug in Beancount then - `Cost`s should always have a date.

**Comment by tbm** [comment]
I'll file a bug

**Comment by tbm** [comment]
Yes, I have the latest version.

Bug here: https://bitbucket.org/blais/beancount/issues/242/unorderable-types-nonetype-datetimedate

**Comment by yagebu** [comment]
I'll try to handle this more cleanly on our side too - we should at least bubble up the Beancount error.
