### ISSUE TITLE
Exception in find_entry_lines

### ISSUE THREAD

**Issue by fold0** [beancount/fava#772]
I came across the exception below when trying to view details of a last transaction in a ledger file. Looks like there's a missing bounds check there. Software version: fava 1.7 from pip.

```
Traceback (most recent call last):
  File "/s/home/ivank/.local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/s/home/ivank/.local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/s/home/ivank/.local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/s/home/ivank/.local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/s/home/ivank/.local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/s/home/ivank/.local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/s/home/ivank/.local/lib/python3.6/site-packages/fava/application.py", line 277, in report
    return render_template('{}.html'.format(report_name))
  File "/s/home/ivank/.local/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/s/home/ivank/.local/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/s/home/ivank/.local/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/s/home/ivank/.local/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/s/home/ivank/.local/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/s/home/ivank/.local/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/s/home/ivank/.local/lib/python3.6/site-packages/fava/templates/_context.html", line 2, in top-level template code
    {% set entry, balances, slice, sha256sum = ledger.context(entry_hash) %}
  File "/s/home/ivank/.local/lib/python3.6/site-packages/fava/core/__init__.py", line 401, in context
    source_slice, sha256sum = get_entry_slice(entry)
  File "/s/home/ivank/.local/lib/python3.6/site-packages/fava/core/file.py", line 218, in get_entry_slice
    entry_lines = find_entry_lines(lines, entry.meta['lineno'] - 1)
  File "/s/home/ivank/.local/lib/python3.6/site-packages/fava/core/file.py", line 193, in find_entry_lines
    line = lines[lineno]
IndexError: list index out of range
```

**Comment by fold0** [comment]
Reproducible on live demo at URL https://fava.pythonanywhere.com/example-with-budgets/download-journal/

**Comment by yagebu** [comment]
Thanks for the report. I guess this happens when the file was changed on disk (so that the given entry does not exist anymore).
