### ISSUE TITLE
UnboundLocalError: local variable 'mod' referenced before assignment

### ISSUE THREAD

**Issue by alexiri** [beancount/fava#844]
I'm seeing the following error with the latest (3c2b4ad7c1f2b2f0372da1ae563ff8d2df3475fd) code from master. Looking at the code, there must be some problem with one of my importers, but in any case this shouldn't fail like this.

```
alex_1          | Exception on /alexs-beancount/api/changed/ [GET]
alex_1          | Traceback (most recent call last):
alex_1          |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
alex_1          |     response = self.full_dispatch_request()
alex_1          |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
alex_1          |     rv = self.handle_user_exception(e)
alex_1          |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
alex_1          |     reraise(exc_type, exc_value, tb)
alex_1          |   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
alex_1          |     raise value
alex_1          |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1811, in full_dispatch_request
alex_1          |     rv = self.preprocess_request()
alex_1          |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2081, in preprocess_request
alex_1          |     func(request.endpoint, request.view_args)
alex_1          |   File "/usr/local/lib/python3.6/site-packages/fava/application.py", line 218, in _pull_beancount_file
alex_1          |     _load_file()
alex_1          |   File "/usr/local/lib/python3.6/site-packages/fava/application.py", line 90, in _load_file
alex_1          |     ledger = FavaLedger(filepath)
alex_1          |   File "/usr/local/lib/python3.6/site-packages/fava/core/__init__.py", line 167, in __init__
alex_1          |     self.load_file()
alex_1          |   File "/usr/local/lib/python3.6/site-packages/fava/core/__init__.py", line 202, in load_file
alex_1          |     getattr(self, mod).load_file()
alex_1          |   File "/usr/local/lib/python3.6/site-packages/fava/core/ingest.py", line 48, in load_file
alex_1          |     self.config = mod['CONFIG']
alex_1          | UnboundLocalError: local variable 'mod' referenced before assignment
```

**Comment by yagebu** [comment]
Thanks!

**Comment by alexiri** [comment]
I'm not sure this is a good fix. It may show the error in my importer, but `mod['CONFIG']` will still be undefined.

**Comment by yagebu** [comment]
> but mod['CONFIG'] will still be referenced before assignment.

Where?

**Comment by alexiri** [comment]
Oops, sorry, I missed the `return`.
