### ISSUE TITLE
IndexError when opening transaction editor if no newline at the end of the file

### ISSUE THREAD

**Issue by elohmeier** [beancount/fava#865]
I'm using fava 1.7.

Given the following sample beancount file (without a newline at the end):
```
* Options
option "title" "sample"
option "operating_currency" "EUR"

plugin "beancount.plugins.auto_accounts"

2018-12-09 * "sample"
  Assets:A -1.00 EUR
  Expenses:B
```

I can open fava just fine and view the transaction in the journal, but when opening the transaction by clicking on the date in the journal, there is an error in the web ui:
> The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

On the console:
```
Exception on /sample/_context/ [GET]
Traceback (most recent call last):
  File "/nix/store/d1zhjhipx8rq7dgpmy92x03cw7bcvq23-python3.7-Flask-1.0.2/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/nix/store/d1zhjhipx8rq7dgpmy92x03cw7bcvq23-python3.7-Flask-1.0.2/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/nix/store/d1zhjhipx8rq7dgpmy92x03cw7bcvq23-python3.7-Flask-1.0.2/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/nix/store/d1zhjhipx8rq7dgpmy92x03cw7bcvq23-python3.7-Flask-1.0.2/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/nix/store/d1zhjhipx8rq7dgpmy92x03cw7bcvq23-python3.7-Flask-1.0.2/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/nix/store/d1zhjhipx8rq7dgpmy92x03cw7bcvq23-python3.7-Flask-1.0.2/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/nix/store/iwgv03k1xxpvsz5m6mdz7a34knv7m2yb-fava-1.7/lib/python3.7/site-packages/fava/application.py", line 277, in report
    return render_template('{}.html'.format(report_name))
  File "/nix/store/d1zhjhipx8rq7dgpmy92x03cw7bcvq23-python3.7-Flask-1.0.2/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/nix/store/d1zhjhipx8rq7dgpmy92x03cw7bcvq23-python3.7-Flask-1.0.2/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/nix/store/nfz5ps6pa3x6iw50bwzdhzzj2darb3yw-python3.7-Jinja2-2.10/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/nix/store/nfz5ps6pa3x6iw50bwzdhzzj2darb3yw-python3.7-Jinja2-2.10/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/nix/store/nfz5ps6pa3x6iw50bwzdhzzj2darb3yw-python3.7-Jinja2-2.10/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/nix/store/nfz5ps6pa3x6iw50bwzdhzzj2darb3yw-python3.7-Jinja2-2.10/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/nix/store/iwgv03k1xxpvsz5m6mdz7a34knv7m2yb-fava-1.7/lib/python3.7/site-packages/fava/templates/_context.html", line 2, in top-level template code
    {% set entry, balances, slice, sha256sum = ledger.context(entry_hash) %}
  File "/nix/store/iwgv03k1xxpvsz5m6mdz7a34knv7m2yb-fava-1.7/lib/python3.7/site-packages/fava/core/__init__.py", line 401, in context
    source_slice, sha256sum = get_entry_slice(entry)
  File "/nix/store/iwgv03k1xxpvsz5m6mdz7a34knv7m2yb-fava-1.7/lib/python3.7/site-packages/fava/core/file.py", line 218, in get_entry_slice
    entry_lines = find_entry_lines(lines, entry.meta['lineno'] - 1)
  File "/nix/store/iwgv03k1xxpvsz5m6mdz7a34knv7m2yb-fava-1.7/lib/python3.7/site-packages/fava/core/file.py", line 193, in find_entry_lines
    line = lines[lineno]
IndexError: list index out of range
127.0.0.1 - - [11/Jan/2019 19:08:12] "GET /sample/_context/?entry_hash=854ef668c6bf491ecaa3bc420672eb5c HTTP/1.1" 500 -
```

If I append a newline to the beancount file the editor opens as expected.

**Comment by elohmeier** [comment]
Nevermind, this bug is not affecting v1.9... :)

**Comment by elohmeier** [comment]
related: https://github.com/NixOS/nixpkgs/pull/53937
