### ISSUE TITLE
Internal server error on posting with invalid cost

### ISSUE THREAD

**Issue by lluchs** [beancount/fava#869]
Minimal reproduction:

```
2019-01-20 *
  Assets:AccountB 1 ABC {2}
```

Results in the following error:

```
Exception on /beancount/errors/ [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/fava/core/charts.py", line 31, in default
    return JSONEncoder.default(self, o)
  File "/usr/lib/python3.7/site-packages/flask/json/__init__.py", line 81, in default
    return _json.JSONEncoder.default(self, o)
  File "/home/lukas/.local/lib/python3.7/site-packages/simplejson/encoder.py", line 273, in default
    o.__class__.__name__)
TypeError: Object of type DisplayContext is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.7/site-packages/fava/application.py", line 310, in report
    return render_template("{}.html".format(report_name))
  File "/usr/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/usr/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/usr/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.7/site-packages/fava/templates/errors.html", line 4, in top-level template code
    {% set page_title = _('Errors') %}
  File "/usr/lib/python3.7/site-packages/fava/templates/_layout.html", line 60, in top-level template code
    }|tojson|safe }}</script>
  File "/usr/lib/python3.7/site-packages/flask/json/__init__.py", line 327, in tojson_filter
    return Markup(htmlsafe_dumps(obj, **kwargs))
  File "/usr/lib/python3.7/site-packages/flask/json/__init__.py", line 242, in htmlsafe_dumps
    rv = dumps(obj, **kwargs) \
  File "/usr/lib/python3.7/site-packages/flask/json/__init__.py", line 179, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/home/lukas/.local/lib/python3.7/site-packages/simplejson/__init__.py", line 399, in dumps
    **kw).encode(obj)
  File "/home/lukas/.local/lib/python3.7/site-packages/simplejson/encoder.py", line 296, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/lukas/.local/lib/python3.7/site-packages/simplejson/encoder.py", line 378, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.7/site-packages/fava/core/charts.py", line 33, in default
    return str(o)
  File "/usr/lib/python3.7/site-packages/beancount/core/display_context.py", line 190, in __str__
    for currency, ccontext in sorted(self.ccontexts.items()):
TypeError: '<' not supported between instances of 'type' and 'str'
```

**Comment by yagebu** [comment]
This is a Beancount bug, I've added a PR with a fix: https://bitbucket.org/blais/beancount/pull-requests/95/do-not-update-display-context-if-currency/diff

**Comment by yagebu** [comment]
This will be fixed with the next Beancount release.
