### ISSUE TITLE
Fixed price not working

### ISSUE THREAD

**Issue by danuker** [beancount/fava#893]
When I try to add a currency with a fixed total amount using the new-transaction interface (with the `@@` operator), I get an internal server error:

```
Income:Salary       -237.5 RON @@ 50 EUR
Assets:Checking-Account 50 EUR
```

```
Exception on /beancount/api/add-entries/ [PUT]
Traceback (most recent call last):
  File "/home/dan/.local/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dan/.local/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dan/.local/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dan/.local/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/dan/.local/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dan/.local/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dan/.local/lib/python3.7/site-packages/fava/json_api.py", line 42, in _wrapper
    return func(request_data)
  File "/home/dan/.local/lib/python3.7/site-packages/fava/json_api.py", line 26, in _wrapper
    json_data = func(*args, **kwargs)
  File "/home/dan/.local/lib/python3.7/site-packages/fava/json_api.py", line 175, in add_entries
    entries = [deserialise(entry) for entry in request_data["entries"]]
  File "/home/dan/.local/lib/python3.7/site-packages/fava/json_api.py", line 175, in <listcomp>
    entries = [deserialise(entry) for entry in request_data["entries"]]
  File "/home/dan/.local/lib/python3.7/site-packages/fava/serialisation.py", line 114, in deserialise
    postings = [deserialise_posting(pos) for pos in json_entry["postings"]]
  File "/home/dan/.local/lib/python3.7/site-packages/fava/serialisation.py", line 114, in <listcomp>
    postings = [deserialise_posting(pos) for pos in json_entry["postings"]]
  File "/home/dan/.local/lib/python3.7/site-packages/fava/serialisation.py", line 88, in deserialise_posting
    amount, raw_price = amount.split("@")
ValueError: too many values to unpack (expected 2)
```

It works if I use the text editor, however.

This is with Fava version 1.10 from Pip.

**Comment by yagebu** [comment]
That syntax is currently not supported in the web UI. Internally, Beancount also doesn't support it, it's directly converted to the corresponding `@` version. Since we're using Beancount's structures, the `@@` would never end up in the file and we'd introduce rounding errors or end up with lots of digits in the output, so I'm somewhat hesitant to add support for it.
