### ISSUE TITLE
Loading entry context failed

### ISSUE THREAD

**Issue by kiney** [beancount/fava#895]
In the current HEAD when I click on a transaction in journal view it fails with
`Loading entry context failed.`
in the gui.
The version (1.10) i installed with pip works just fine.
I think it was introduced with commit c5ad85f but I still don't understand the exact reason...

exact traceback from console:
```
Exception on /vtth-kassenbuch/_context/ [GET]
Traceback (most recent call last):
  File "/home/kiney/tmp/fava/env/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kiney/tmp/fava/env/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kiney/tmp/fava/env/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kiney/tmp/fava/env/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/kiney/tmp/fava/env/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kiney/tmp/fava/env/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kiney/tmp/fava/fava/application.py", line 308, in report
    return render_template("_layout.html", active_page=report_name)
  File "/home/kiney/tmp/fava/env/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/kiney/tmp/fava/env/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/kiney/tmp/fava/env/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/kiney/tmp/fava/env/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/kiney/tmp/fava/env/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kiney/tmp/fava/env/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/kiney/tmp/fava/fava/templates/_layout.html", line 3, in top-level template code
    {% set page_title = globals.all_pages[active_page].0 if not page_title else page_title %}
  File "/home/kiney/tmp/fava/env/lib/python3.6/site-packages/jinja2/environment.py", line 411, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'dict object' has no attribute '_context'

```

**Comment by yagebu** [comment]
Thanks for the report! This is due to a change that tries to render all pages in the standard layout by default - which shouldn't be done for the entry context...
