### ISSUE TITLE
Bug Report: Changes & Balances views

### ISSUE THREAD

**Issue by g40matt** [beancount/fava#950]
I loaded up the dev version this evening and ran into a bug in the Changes & Balances views.  After I select an account from the Income Statement or Balance Sheet, the Account Journal loads properly.  Clicking either Changes or Balances fails with a "TypeError: expected string or bytes-like object."  

Exception on /main-ledger/account/Liabilities:Credit-Cards:Amex-BC/balances/ [GET]
Traceback (most recent call last):
  File "/home/pi/fava/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/fava/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/fava/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/fava/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pi/fava/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/fava/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/fava/fava/application.py", line 264, in account
    "account.html", account_name=name, subreport=subreport
  File "/home/pi/fava/venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/pi/fava/venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/pi/fava/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/pi/fava/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/pi/fava/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/fava/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/pi/fava/fava/templates/account.html", line 10, in top-level template code
    {% set journal = subreport == 'journal' %}
  File "/home/pi/fava/fava/templates/_layout.html", line 42, in top-level template code
    {% block content %}
  File "/home/pi/fava/fava/templates/account.html", line 37, in block "content"
    {{ tree_table.account_tree(account_name, interval_balances, dates, accumulate) }}
  File "/home/pi/fava/venv/lib/python3.6/site-packages/jinja2/runtime.py", line 579, in _invoke
    rv = self._func(*arguments)
  File "/home/pi/fava/fava/templates/_tree_table.html", line 99, in template
    {% for account in [interval_balances[0]|get_or_create(account_name)] recursive %}
  File "/home/pi/fava/fava/templates/_tree_table.html", line 100, in template
    <li{{ ' class=toggled' if account.name|collapse_account else '' }}>
  File "/home/pi/fava/fava/template_filters.py", line 192, in collapse_account
    if re.match(pattern, account_name):
  File "/home/pi/fava/venv/lib/python3.6/re.py", line 172, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object

**Comment by yagebu** [comment]
Thanks for the bug report!
