### ISSUE TITLE
Support total cost of currency conversion in editor

### ISSUE THREAD

**Issue by yhylord** [beancount/fava#955]
When I add an entry using the editor, if the entry involves a foreign currency, and I use `@@` to specify its cost in the local currency, Fava would complain seeing too many `@` and throw an internal server error.

Take the example from the syntax doc and try entering it yourself:
```
2012-11-03 * "Transfer to account in Canada"
  Assets:MyBank:Checking            -400.00 USD @@ 436.01 CAD
  Assets:FR:SocGen:Checking          436.01 CAD
```
Output in the terminal:
```python
Exception on /beancount/api/add-entries/ [PUT]
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.7/site-packages/fava/json_api.py", line 42, in _wrapper
    return func(request_data)
  File "/usr/lib/python3.7/site-packages/fava/json_api.py", line 26, in _wrapper
    json_data = func(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/fava/json_api.py", line 175, in add_entries
    entries = [deserialise(entry) for entry in request_data["entries"]]
  File "/usr/lib/python3.7/site-packages/fava/json_api.py", line 175, in <listcomp>
    entries = [deserialise(entry) for entry in request_data["entries"]]
  File "/usr/lib/python3.7/site-packages/fava/serialisation.py", line 114, in deserialise
    postings = [deserialise_posting(pos) for pos in json_entry["postings"]]
  File "/usr/lib/python3.7/site-packages/fava/serialisation.py", line 114, in <listcomp>
    postings = [deserialise_posting(pos) for pos in json_entry["postings"]]
  File "/usr/lib/python3.7/site-packages/fava/serialisation.py", line 88, in deserialise_posting
    amount, raw_price = amount.split("@")
ValueError: too many values to unpack (expected 2)
```

**Comment by pmarciniak** [comment]
I've run into this problem a while ago and have kept a hack locally to work around it. The problem here is that AFAICT beancount API (data.Posting) doesn't support this notation, so the only thing we can do is convert the total price to a unit price and store that.

Anyway, I've published my hack, so feel free to give it a go: https://github.com/pmarciniak/fava/tree/insert-entry (especially commit bc15b3b41784fbb2f6479b61fb2cf2b66b30f731)

**Comment by yagebu** [comment]
@pmarciniak: I would call your hack the correct fix :) Can you submit a PR?

**Comment by pmarciniak** [comment]
OK, I submitted the PR :)
FWIW, I still think this is not the optimal solution as it silently changes what the user typed into the transaction entry dialog before writing it to the output file, but it's better than nothing.

I tried to describe in the commit what I think would need to happen to handle this cleanly.

**Comment by pmarciniak** [comment]
Actually, I just found out that this topic has been discussed at large in the past (e.g. https://bitbucket.org/blais/beancount/issues/194/use-of-syntax-was-use-of-float-numbers-in)

With this new knowledge, I agree that my PR is the right thing to do given the current Beancount design choice, as it effectively mirrors Beancount logic. (https://bitbucket.org/blais/beancount/src/621cec5ed38bcd128a3502a3b5c367f283deffe2/beancount/parser/grammar.py?at=default&fileviewer=file-view-default#grammar.py-806)

I'm still not happy that the exact total price gets lost in the translation, but this is an orthogonal issue now.

**Comment by yagebu** [comment]
> I'm still not happy that the exact total price gets lost in the translation, but this is an orthogonal issue now.

As was suggested in the Beancount issue, we could use metadata to pass it through to the file. Since the total price would still get lost on parsing the file, I wouldn't put energy into it since I think it's fine to make that explicit on import (in Fava).
